//! `UniFFI` bridge exposing the native Cascade engine to Swift and Kotlin.
//!
//! A mobile node (an iOS File Provider extension, an Android `DocumentsProvider`)
//! drives the same [`cascade_engine::NativeEngine`] the desktop daemon uses, over
//! a small object-oriented surface generated by `UniFFI`. The bridge is deliberately
//! thin: every method forwards to an existing engine call, adding only the path
//! plumbing and error mapping the foreign side needs. It builds the engine without
//! the `exec` feature so it cross-compiles to `aarch64-apple-ios`, where a mobile
//! node has no PTY or process-exec capability anyway.
//!
//! The API is declared with proc-macros only — no UDL — so [`uniffi::setup_scaffolding`]
//! emits the scaffolding and `src/bin/uniffi-bindgen.rs` emits the foreign glue.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use cascade_engine::backend::{Backend, MountedBackend};
use cascade_engine::{EngineConfig, EngineHandle, NativeEngine};

uniffi::setup_scaffolding!();

/// The subdirectory of the node's config directory that the local backend mirrors.
///
/// A mobile node presents one local-files backend rooted here; on-demand reads,
/// listings, and pins all route into it. The directory is created on construction
/// so the backend, which refuses a non-existent root, always has somewhere to bind.
const NODE_FILES_DIR: &str = "files";

/// The mount prefix the local backend is bound to under the neutral VFS root.
///
/// Paths handed to [`CascadeNode::list_dir`], [`CascadeNode::read_file`], and the
/// pin verbs are VFS-absolute and begin with this segment (for example
/// `local/Documents/report.txt`).
const NODE_MOUNT: &str = "local";

/// The backend identifier recorded in the state database for the node's files.
const NODE_BACKEND_ID: &str = "local";

/// A single entry returned by [`CascadeNode::list_dir`].
///
/// Mirrors [`cascade_engine::types::DirEntry`] across the FFI boundary as a plain
/// record the foreign side can map straight onto its own directory-entry type.
#[derive(Debug, uniffi::Record)]
pub struct DirEntry {
    /// The entry's final path segment (no parent path).
    pub name: String,
    /// Whether the entry is a directory.
    pub is_dir: bool,
}

/// Errors surfaced to the foreign side.
///
/// The engine works in [`anyhow::Error`]; every fallible bridge method collapses
/// that into one of these variants so Swift and Kotlin see a typed error rather
/// than an opaque string. The carried message is the underlying error's display
/// form, preserved for logging on the foreign side.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum CascadeError {
    /// The node's config directory could not be created or prepared.
    ///
    /// The field is named `detail` rather than `message` deliberately: the
    /// Kotlin bindings generator maps each error variant onto a subclass of
    /// `kotlin.Exception`, and a variant field literally called `message` collides
    /// with `Throwable.message`, producing Kotlin that does not compile. Swift
    /// has no such clash, so this rename only changes the (unread) field name on
    /// the Swift side.
    #[error("config error: {detail}")]
    Config { detail: String },
    /// The engine could not be constructed or started.
    #[error("engine error: {detail}")]
    Engine { detail: String },
    /// A directory listing failed.
    #[error("listing error: {detail}")]
    Listing { detail: String },
    /// A file read failed.
    #[error("read error: {detail}")]
    Read { detail: String },
    /// A pin or unpin operation failed.
    #[error("pin error: {detail}")]
    Pin { detail: String },
}

/// A running Cascade node, wrapping a [`NativeEngine`].
///
/// Constructed with [`CascadeNode::new`], which builds the engine over a state
/// database and cache directory rooted at the caller-supplied config directory and
/// mounts a single local-files backend. The object owns the engine for its
/// lifetime; dropping it on the foreign side shuts the background workers down.
#[derive(Debug, uniffi::Object)]
pub struct CascadeNode {
    engine: Arc<NativeEngine>,
    /// The handle for the background cache worker spawned by [`CascadeNode::start`].
    ///
    /// Held so a subsequent [`CascadeNode::stop`] (via the engine's cancellation
    /// flag) quiesces the worker that this handle joins. `None` until `start` runs.
    handle: tokio::sync::Mutex<Option<EngineHandle>>,
}

#[uniffi::export(async_runtime = "tokio")]
impl CascadeNode {
    /// Build a node rooted at `config_dir`.
    ///
    /// Creates `config_dir` and its `files` subdirectory, opens (or creates) the
    /// state database at `config_dir/state.db`, and mounts a local-files backend
    /// over the `files` directory under the `local` VFS prefix. The engine is built
    /// on the calling Tokio runtime — `UniFFI` drives this async constructor on the
    /// runtime the rest of the methods also use, so the engine's captured runtime
    /// handle is the one its later async work runs on.
    #[uniffi::constructor]
    pub async fn new(config_dir: String) -> Result<Arc<Self>, CascadeError> {
        let config_root = PathBuf::from(&config_dir);
        let files_dir = config_root.join(NODE_FILES_DIR);
        tokio::fs::create_dir_all(&files_dir)
            .await
            .map_err(|e| CascadeError::Config {
                detail: format!("create config dir {}: {e}", files_dir.display()),
            })?;

        let backend = build_local_backend(&files_dir)?;
        let config = EngineConfig {
            db_path: config_root.join("state.db"),
            mount_point: config_root.clone(),
            backends: vec![MountedBackend::new(Some(NODE_MOUNT.to_owned()), backend)],
            cache_dir: Some(config_root.join("cache")),
            enable_p2p: false,
            p2p_data_dir: None,
            p2p_posture: None,
            p2p_relay_endpoints: Vec::new(),
            p2p_relay_shared_secret: None,
            backend_factory: None,
        };
        let engine = NativeEngine::new(config).map_err(|e| CascadeError::Engine {
            detail: format!("build engine: {e}"),
        })?;
        Ok(Arc::new(Self {
            engine: Arc::new(engine),
            handle: tokio::sync::Mutex::new(None),
        }))
    }

    /// Start the engine's background workers (cache eviction).
    ///
    /// Idempotent in effect: a second call replaces the stored handle, leaving the
    /// engine's single cancellation flag governing the workers.
    pub async fn start(&self) -> Result<(), CascadeError> {
        let started = self.engine.start().map_err(|e| CascadeError::Engine {
            detail: format!("start engine: {e}"),
        })?;
        *self.handle.lock().await = Some(started);
        Ok(())
    }

    /// Stop the engine's background workers, signalling them to quiesce.
    pub async fn stop(&self) {
        self.engine.shutdown();
        self.handle.lock().await.take();
    }

    /// Return the engine status as a JSON object.
    ///
    /// Serialising to JSON keeps the foreign surface a single string rather than a
    /// mirror of the whole [`cascade_engine::EngineStatus`] tree, which the File
    /// Provider only needs to display, not to branch on.
    pub async fn status(&self) -> String {
        let status = self.engine.status().await;
        serde_json::json!({
            "running": status.running,
            "backends": status.backends,
            "cache": {
                "online": status.cache_stats.online_count,
                "cached": status.cache_stats.cached_count,
                "pinned": status.cache_stats.pinned_count,
                "total_bytes": status.cache_stats.total_bytes,
            },
            "p2p_enabled": status.p2p_enabled,
            "p2p_device_id": status.p2p_device_id,
        })
        .to_string()
    }

    /// List the entries of the directory at `path` (a VFS-absolute path).
    pub async fn list_dir(&self, path: String) -> Result<Vec<DirEntry>, CascadeError> {
        let tree = self.engine.vfs().clone();
        // The VFS tree sits behind a synchronous lock and the backend listing is
        // async, so resolve the routing and injection set under the guard, release
        // it, then await the backend — the same discipline the engine's own
        // presenters follow to avoid holding a std lock across an await point.
        let (backend, backend_path, mount_names) = {
            let guard = tree.read().map_err(|_| CascadeError::Listing {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            guard
                .resolve_listing(Path::new(&path))
                .map_err(|e| CascadeError::Listing {
                    detail: format!("resolve {path}: {e}"),
                })?
        };
        let entries = list_via_backend(backend, &backend_path, &mount_names).await?;
        Ok(entries
            .into_iter()
            .map(|e| DirEntry {
                name: e.name,
                is_dir: e.is_dir,
            })
            .collect())
    }

    /// Read the full contents of the file at `path` (a VFS-absolute path).
    pub async fn read_file(&self, path: String) -> Result<Vec<u8>, CascadeError> {
        let tree = self.engine.vfs().clone();
        let (backend, rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Read {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (backend, rel) = guard.resolve(Path::new(&path));
            (Arc::clone(backend), rel)
        };
        let entry = backend
            .metadata(&rel)
            .await
            .map_err(|e| CascadeError::Read {
                detail: format!("metadata {path}: {e}"),
            })?;
        backend
            .download(&entry)
            .await
            .map_err(|e| CascadeError::Read {
                detail: format!("download {path}: {e}"),
            })
    }

    /// Pin the path pattern so matching files are kept on disk.
    pub async fn pin(&self, path: String) -> Result<(), CascadeError> {
        self.engine
            .pin(&path, true)
            .await
            .map_err(|e| CascadeError::Pin {
                detail: format!("pin {path}: {e}"),
            })
    }

    /// Unpin the path pattern. A no-op if no matching rule exists.
    pub async fn unpin(&self, path: String) -> Result<(), CascadeError> {
        self.engine
            .unpin(&path)
            .await
            .map(|_removed| ())
            .map_err(|e| CascadeError::Pin {
                detail: format!("unpin {path}: {e}"),
            })
    }
}

/// List a directory through an already-resolved backend, reproducing the merge
/// that [`cascade_engine::vfs::VfsTree::read_dir`] performs internally.
///
/// Split out so [`CascadeNode::list_dir`] can release the synchronous VFS lock
/// before awaiting the backend's listing.
async fn list_via_backend(
    backend: Arc<dyn Backend>,
    backend_path: &str,
    mount_names: &[String],
) -> Result<Vec<cascade_engine::types::DirEntry>, CascadeError> {
    let native_id = cascade_engine::vfs::resolve_listing_native_id(backend.as_ref(), backend_path)
        .await
        .map_err(|e| CascadeError::Listing {
            detail: format!("resolve native id for {backend_path}: {e}"),
        })?;
    let children = backend
        .list_children(&native_id)
        .await
        .map_err(|e| CascadeError::Listing {
            detail: format!("list children of {backend_path}: {e}"),
        })?;
    Ok(cascade_engine::vfs::merge_listing(children, mount_names))
}

/// Build the local-files backend rooted at `files_dir`.
///
/// The backend is configured through its public `create_backend` TOML contract;
/// the directory is created by the caller before this runs, satisfying the
/// backend's requirement that its root already exist.
fn build_local_backend(files_dir: &Path) -> Result<Arc<dyn Backend>, CascadeError> {
    let root = files_dir.to_str().ok_or_else(|| CascadeError::Config {
        detail: format!("config path is not valid UTF-8: {}", files_dir.display()),
    })?;
    let mut table = toml::value::Table::new();
    table.insert(
        "id".to_owned(),
        toml::Value::String(NODE_BACKEND_ID.to_owned()),
    );
    table.insert("root_path".to_owned(), toml::Value::String(root.to_owned()));
    table.insert("mode".to_owned(), toml::Value::String("mirror".to_owned()));
    let config = toml::Value::Table(table);
    let backend =
        cascade_backend_local::create_backend(&config).map_err(|e| CascadeError::Config {
            detail: format!("build local backend: {e}"),
        })?;
    Ok(Arc::from(backend))
}
