//! `UniFFI` bridge exposing the native Cascade engine to Swift and Kotlin.
//!
//! A mobile node (an iOS File Provider extension, an Android `DocumentsProvider`)
//! drives the same [`cascade_engine::NativeEngine`] the desktop daemon uses, over
//! a small object-oriented surface generated by `UniFFI`. The bridge is deliberately
//! thin: every method forwards to an existing engine call, adding only the path
//! plumbing and error mapping the foreign side needs. It builds the engine without
//! the `exec` feature so it cross-compiles to `aarch64-apple-ios`, where a mobile
//! node has no PTY or process-exec capability anyway.
//!
//! The API is declared with proc-macros only — no UDL — so [`uniffi::setup_scaffolding`]
//! emits the scaffolding and `src/bin/uniffi-bindgen.rs` emits the foreign glue.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use cascade_engine::backend::{Backend, MountedBackend};
use cascade_engine::{EngineConfig, EngineHandle, NativeEngine};

uniffi::setup_scaffolding!();

/// The subdirectory of the node's config directory that the local backend mirrors.
///
/// A mobile node presents one local-files backend rooted here; on-demand reads,
/// listings, and pins all route into it. The directory is created on construction
/// so the backend, which refuses a non-existent root, always has somewhere to bind.
const NODE_FILES_DIR: &str = "files";

/// The mount prefix the local backend is bound to under the neutral VFS root.
///
/// Paths handed to [`CascadeNode::list_dir`], [`CascadeNode::read_file`], and the
/// pin verbs are VFS-absolute and begin with this segment (for example
/// `local/Documents/report.txt`).
const NODE_MOUNT: &str = "local";

/// The backend identifier recorded in the state database for the node's files.
const NODE_BACKEND_ID: &str = "local";

/// A single entry returned by [`CascadeNode::list_dir`].
///
/// Mirrors [`cascade_engine::types::DirEntry`] across the FFI boundary as a plain
/// record the foreign side can map straight onto its own directory-entry type.
#[derive(Debug, uniffi::Record)]
pub struct DirEntry {
    /// The entry's final path segment (no parent path).
    pub name: String,
    /// Whether the entry is a directory.
    pub is_dir: bool,
}

/// Errors surfaced to the foreign side.
///
/// The engine works in [`anyhow::Error`]; every fallible bridge method collapses
/// that into one of these variants so Swift and Kotlin see a typed error rather
/// than an opaque string. The carried message is the underlying error's display
/// form, preserved for logging on the foreign side.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum CascadeError {
    /// The node's config directory could not be created or prepared.
    ///
    /// The field is named `detail` rather than `message` deliberately: the
    /// Kotlin bindings generator maps each error variant onto a subclass of
    /// `kotlin.Exception`, and a variant field literally called `message` collides
    /// with `Throwable.message`, producing Kotlin that does not compile. Swift
    /// has no such clash, so this rename only changes the (unread) field name on
    /// the Swift side.
    #[error("config error: {detail}")]
    Config { detail: String },
    /// The engine could not be constructed or started.
    #[error("engine error: {detail}")]
    Engine { detail: String },
    /// A directory listing failed.
    #[error("listing error: {detail}")]
    Listing { detail: String },
    /// A file read failed.
    #[error("read error: {detail}")]
    Read { detail: String },
    /// A pin or unpin operation failed.
    #[error("pin error: {detail}")]
    Pin { detail: String },
    /// A write operation (upload, create directory, delete, or rename) failed.
    #[error("write error: {detail}")]
    Write { detail: String },
}

/// A running Cascade node, wrapping a [`NativeEngine`].
///
/// Constructed with [`CascadeNode::new`], which builds the engine over a state
/// database and cache directory rooted at the caller-supplied config directory and
/// mounts a single local-files backend. The object owns the engine for its
/// lifetime; dropping it on the foreign side shuts the background workers down.
#[derive(Debug, uniffi::Object)]
pub struct CascadeNode {
    engine: Arc<NativeEngine>,
    /// The handle for the background cache worker spawned by [`CascadeNode::start`].
    ///
    /// Held so a subsequent [`CascadeNode::stop`] (via the engine's cancellation
    /// flag) quiesces the worker that this handle joins. `None` until `start` runs.
    handle: tokio::sync::Mutex<Option<EngineHandle>>,
}

#[uniffi::export(async_runtime = "tokio")]
impl CascadeNode {
    /// Build a node rooted at `config_dir`.
    ///
    /// Creates `config_dir` and its `files` subdirectory, opens (or creates) the
    /// state database at `config_dir/state.db`, and mounts a local-files backend
    /// over the `files` directory under the `local` VFS prefix. The engine is built
    /// on the calling Tokio runtime — `UniFFI` drives this async constructor on the
    /// runtime the rest of the methods also use, so the engine's captured runtime
    /// handle is the one its later async work runs on.
    #[uniffi::constructor]
    pub async fn new(config_dir: String) -> Result<Arc<Self>, CascadeError> {
        let config_root = PathBuf::from(&config_dir);
        let files_dir = config_root.join(NODE_FILES_DIR);
        tokio::fs::create_dir_all(&files_dir)
            .await
            .map_err(|e| CascadeError::Config {
                detail: format!("create config dir {}: {e}", files_dir.display()),
            })?;

        let backend = build_local_backend(&files_dir)?;
        let config = EngineConfig {
            db_path: config_root.join("state.db"),
            mount_point: config_root.clone(),
            backends: vec![MountedBackend::new(Some(NODE_MOUNT.to_owned()), backend)],
            cache_dir: Some(config_root.join("cache")),
            enable_p2p: false,
            p2p_data_dir: None,
            p2p_posture: None,
            p2p_relay_endpoints: Vec::new(),
            p2p_relay_shared_secret: None,
            backend_factory: None,
        };
        let engine = NativeEngine::new(config).map_err(|e| CascadeError::Engine {
            detail: format!("build engine: {e}"),
        })?;
        Ok(Arc::new(Self {
            engine: Arc::new(engine),
            handle: tokio::sync::Mutex::new(None),
        }))
    }

    /// Start the engine's background workers (cache eviction).
    ///
    /// Idempotent in effect: a second call replaces the stored handle, leaving the
    /// engine's single cancellation flag governing the workers.
    pub async fn start(&self) -> Result<(), CascadeError> {
        let started = self.engine.start().map_err(|e| CascadeError::Engine {
            detail: format!("start engine: {e}"),
        })?;
        *self.handle.lock().await = Some(started);
        Ok(())
    }

    /// Stop the engine's background workers, signalling them to quiesce.
    pub async fn stop(&self) {
        self.engine.shutdown();
        self.handle.lock().await.take();
    }

    /// Return the engine status as a JSON object.
    ///
    /// Serialising to JSON keeps the foreign surface a single string rather than a
    /// mirror of the whole [`cascade_engine::EngineStatus`] tree, which the File
    /// Provider only needs to display, not to branch on.
    pub async fn status(&self) -> String {
        let status = self.engine.status().await;
        serde_json::json!({
            "running": status.running,
            "backends": status.backends,
            "cache": {
                "online": status.cache_stats.online_count,
                "cached": status.cache_stats.cached_count,
                "pinned": status.cache_stats.pinned_count,
                "total_bytes": status.cache_stats.total_bytes,
            },
            "p2p_enabled": status.p2p_enabled,
            "p2p_device_id": status.p2p_device_id,
        })
        .to_string()
    }

    /// List the entries of the directory at `path` (a VFS-absolute path).
    pub async fn list_dir(&self, path: String) -> Result<Vec<DirEntry>, CascadeError> {
        let tree = self.engine.vfs().clone();
        // The VFS tree sits behind a synchronous lock and the backend listing is
        // async, so resolve the routing and injection set under the guard, release
        // it, then await the backend — the same discipline the engine's own
        // presenters follow to avoid holding a std lock across an await point.
        let path = normalise_vfs_path(&path);
        let (backend, backend_path, mount_names) = {
            let guard = tree.read().map_err(|_| CascadeError::Listing {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            guard
                .resolve_listing(Path::new(&path))
                .map_err(|e| CascadeError::Listing {
                    detail: format!("resolve {path}: {e}"),
                })?
        };
        let entries = list_via_backend(backend, &backend_path, &mount_names).await?;
        Ok(entries
            .into_iter()
            .map(|e| DirEntry {
                name: e.name,
                is_dir: e.is_dir,
            })
            .collect())
    }

    /// Read the full contents of the file at `path` (a VFS-absolute path).
    pub async fn read_file(&self, path: String) -> Result<Vec<u8>, CascadeError> {
        let tree = self.engine.vfs().clone();
        let path = normalise_vfs_path(&path);
        let (backend, rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Read {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (backend, rel) = guard.resolve(Path::new(&path));
            (Arc::clone(backend), rel)
        };
        let entry = backend
            .metadata(&rel)
            .await
            .map_err(|e| CascadeError::Read {
                detail: format!("metadata {path}: {e}"),
            })?;
        backend
            .download(&entry)
            .await
            .map_err(|e| CascadeError::Read {
                detail: format!("download {path}: {e}"),
            })
    }

    /// Pin the path pattern so matching files are kept on disk.
    pub async fn pin(&self, path: String) -> Result<(), CascadeError> {
        self.engine
            .pin(&path, true)
            .await
            .map_err(|e| CascadeError::Pin {
                detail: format!("pin {path}: {e}"),
            })
    }

    /// Unpin the path pattern. A no-op if no matching rule exists.
    pub async fn unpin(&self, path: String) -> Result<(), CascadeError> {
        self.engine
            .unpin(&path)
            .await
            .map(|_removed| ())
            .map_err(|e| CascadeError::Pin {
                detail: format!("unpin {path}: {e}"),
            })
    }

    /// Upload a new file at `path` (a VFS-absolute path) with the given bytes.
    ///
    /// If a file already exists at `path` it is overwritten via the backend's
    /// `update` verb; otherwise the `upload` verb creates it. The parent
    /// directory's `FileId` is resolved by walking the backend for the parent
    /// path, mirroring the `WebDAV` presenter's upload flow. Backends that ignore
    /// the parent id (the local backend) accept a best-effort id harmlessly.
    pub async fn upload(&self, path: String, bytes: Vec<u8>) -> Result<(), CascadeError> {
        let tree = self.engine.vfs().clone();
        let path = normalise_vfs_path(&path);
        let (backend, rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Write {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (backend, rel) = guard.resolve(Path::new(&path));
            (Arc::clone(backend), rel)
        };

        // Resolve the parent's FileId so cloud backends that address by id
        // (Google Drive) can place the upload correctly. The local backend
        // ignores this, so a failure to resolve the parent falls back to a
        // root placeholder rather than failing the upload.
        let parent_id = resolve_parent_id(&backend, &rel).await;
        let rel_str = rel.to_string_lossy();
        let existing = backend.metadata(&rel).await;

        if let Ok(entry) = existing {
            let file_id = cascade_engine::types::FileId(entry.id.0.clone());
            backend
                .update(&file_id, &bytes)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("update {path}: {e}"),
                })?;
        } else {
            backend
                .upload(&rel, &bytes, &parent_id)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("upload {path}: {e}"),
                })?;
        }
        let _ = rel_str;
        Ok(())
    }

    /// Create a directory at `path` (a VFS-absolute path).
    pub async fn create_dir(&self, path: String) -> Result<(), CascadeError> {
        let tree = self.engine.vfs().clone();
        let path = normalise_vfs_path(&path);
        let (backend, rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Write {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (backend, rel) = guard.resolve(Path::new(&path));
            (Arc::clone(backend), rel)
        };
        backend
            .create_dir(&rel)
            .await
            .map_err(|e| CascadeError::Write {
                detail: format!("create_dir {path}: {e}"),
            })?;
        Ok(())
    }

    /// Delete the file or directory at `path` (a VFS-absolute path).
    pub async fn delete(&self, path: String) -> Result<(), CascadeError> {
        let tree = self.engine.vfs().clone();
        let path = normalise_vfs_path(&path);
        let (backend, rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Write {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (backend, rel) = guard.resolve(Path::new(&path));
            (Arc::clone(backend), rel)
        };
        let entry = backend
            .metadata(&rel)
            .await
            .map_err(|e| CascadeError::Write {
                detail: format!("metadata {path}: {e}"),
            })?;
        backend
            .delete(&entry)
            .await
            .map_err(|e| CascadeError::Write {
                detail: format!("delete {path}: {e}"),
            })?;
        Ok(())
    }

    /// Rename or move `src` to `dst` (both VFS-absolute paths).
    ///
    /// Same-backend renames call the backend's `move_entry` directly;
    /// cross-backend moves download from the source, upload to the destination,
    /// and delete the original, matching [`cascade_engine::vfs::VfsTree::rename`].
    pub async fn rename(&self, src: String, dst: String) -> Result<(), CascadeError> {
        let tree = self.engine.vfs().clone();
        let src_path = normalise_vfs_path(&src);
        let dst_path = normalise_vfs_path(&dst);
        let (src_backend, src_rel, dst_backend, dst_rel) = {
            let guard = tree.read().map_err(|_| CascadeError::Write {
                detail: "VFS lock poisoned".to_owned(),
            })?;
            let (src_backend, src_rel) = guard.resolve(Path::new(&src_path));
            let (dst_backend, dst_rel) = guard.resolve(Path::new(&dst_path));
            (
                Arc::clone(src_backend),
                src_rel,
                Arc::clone(dst_backend),
                dst_rel,
            )
        };

        if Arc::ptr_eq(&src_backend, &dst_backend) {
            src_backend
                .move_entry(&src_rel, &dst_rel)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("rename {src_path} -> {dst_path}: {e}"),
                })?;
        } else {
            // Cross-backend move: download, upload, delete. Matches VfsTree::rename.
            let entry = src_backend
                .metadata(&src_rel)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("metadata {src_path}: {e}"),
                })?;
            let data = src_backend
                .download(&entry)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("download {src_path}: {e}"),
                })?;
            let parent_id = resolve_parent_id(&dst_backend, &dst_rel).await;
            dst_backend
                .upload(&dst_rel, &data, &parent_id)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("upload {dst_path}: {e}"),
                })?;
            src_backend
                .delete(&entry)
                .await
                .map_err(|e| CascadeError::Write {
                    detail: format!("delete {src_path}: {e}"),
                })?;
        }
        Ok(())
    }
}

/// List a directory through an already-resolved backend, reproducing the merge
/// that [`cascade_engine::vfs::VfsTree::read_dir`] performs internally.
///
/// Split out so [`CascadeNode::list_dir`] can release the synchronous VFS lock
/// before awaiting the backend's listing.
async fn list_via_backend(
    backend: Arc<dyn Backend>,
    backend_path: &str,
    mount_names: &[String],
) -> Result<Vec<cascade_engine::types::DirEntry>, CascadeError> {
    let native_id = cascade_engine::vfs::resolve_listing_native_id(backend.as_ref(), backend_path)
        .await
        .map_err(|e| CascadeError::Listing {
            detail: format!("resolve native id for {backend_path}: {e}"),
        })?;
    let children = backend
        .list_children(&native_id)
        .await
        .map_err(|e| CascadeError::Listing {
            detail: format!("list children of {backend_path}: {e}"),
        })?;
    Ok(cascade_engine::vfs::merge_listing(children, mount_names))
}

/// Resolve the [`cascade_engine::types::FileId`] of the parent directory of a
/// backend-relative path, for the `parent_id` argument of [`Backend::upload`].
///
/// Cloud backends like Google Drive address nodes by opaque id, so an upload
/// needs the parent's id rather than its path. The local backend ignores the
/// parent id. A failure to resolve the parent (for example when the path is at
/// the backend root) falls back to a `{backend_id}:root` placeholder rather
/// than failing the upload, matching the `WebDAV` presenter's fallback. The
/// function is infallible from the caller's perspective for that reason: the
/// upload itself is what surfaces a real placement error.
async fn resolve_parent_id(
    backend: &Arc<dyn Backend>,
    rel: &Path,
) -> cascade_engine::types::FileId {
    use cascade_engine::types::FileId;
    let backend_id = backend.id().to_owned();
    let Some(parent_path) = rel.parent() else {
        return FileId(format!("{backend_id}:root"));
    };
    if parent_path.as_os_str().is_empty() {
        return FileId(format!("{backend_id}:root"));
    }
    match backend.metadata(parent_path).await {
        Ok(entry) => FileId(entry.id.0),
        Err(_) => FileId(format!("{backend_id}:root")),
    }
}

/// Build the local-files backend rooted at `files_dir`.
///
/// The backend is configured through its public `create_backend` TOML contract;
/// the directory is created by the caller before this runs, satisfying the
/// backend's requirement that its root already exist.
fn build_local_backend(files_dir: &Path) -> Result<Arc<dyn Backend>, CascadeError> {
    let root = files_dir.to_str().ok_or_else(|| CascadeError::Config {
        detail: format!("config path is not valid UTF-8: {}", files_dir.display()),
    })?;
    let mut table = toml::value::Table::new();
    table.insert(
        "id".to_owned(),
        toml::Value::String(NODE_BACKEND_ID.to_owned()),
    );
    table.insert("root_path".to_owned(), toml::Value::String(root.to_owned()));
    table.insert("mode".to_owned(), toml::Value::String("mirror".to_owned()));
    let config = toml::Value::Table(table);
    let backend =
        cascade_backend_local::create_backend(&config).map_err(|e| CascadeError::Config {
            detail: format!("build local backend: {e}"),
        })?;
    Ok(Arc::from(backend))
}

/// Strip leading slashes from a caller-supplied VFS path.
///
/// The engine stores mount prefixes relative (see `mount_prefix_from_str`,
/// which strips leading slashes), and `VfsTree::resolve` matches by
/// `strip_prefix` — so an absolute path like `/local` would not match the
/// `local` prefix and fall through to the neutral root. Mobile callers (the
/// iOS File Provider, which encodes paths into item identifiers) pass
/// leading-slash paths, so normalise at this boundary to match the prefix
/// form, the way the desktop presenters do.
fn normalise_vfs_path(path: &str) -> String {
    path.trim_start_matches('/').to_owned()
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::indexing_slicing)]
mod tests {
    //! Host-run unit tests for the FFI bridge. These build a real `NativeEngine`
    //! over a local-files backend in a tempdir and exercise the same methods the
    //! iOS File Provider and Android `DocumentsProvider` call, so a regression in
    //! the mobile entry point fails CI rather than only surfacing on a device.

    use super::*;

    /// Build a node rooted at a fresh tempdir, pre-seeded with `files`, and
    /// return the on-disk `files` dir so tests can seed more after construction.
    async fn node_with_files(
        files: &[(&str, &[u8])],
    ) -> (tempfile::TempDir, PathBuf, Arc<CascadeNode>) {
        let dir = tempfile::tempdir().unwrap();
        let files_dir = dir.path().join(NODE_FILES_DIR);
        std::fs::create_dir_all(&files_dir).unwrap();
        for (name, contents) in files {
            std::fs::write(files_dir.join(name), contents).unwrap();
        }
        let node = CascadeNode::new(dir.path().to_string_lossy().to_string())
            .await
            .expect("node builds");
        (dir, files_dir, node)
    }

    #[tokio::test]
    async fn new_creates_config_and_files_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let config_dir = dir.path().join("node");
        let _node = CascadeNode::new(config_dir.to_string_lossy().to_string())
            .await
            .expect("node builds");
        assert!(config_dir.is_dir(), "config dir created");
        assert!(
            config_dir.join(NODE_FILES_DIR).is_dir(),
            "files subdir created"
        );
    }

    #[tokio::test]
    async fn status_returns_valid_json_with_expected_shape() {
        let (_dir, _files, node) = node_with_files(&[]).await;
        let status = node.status().await;
        let value: serde_json::Value = serde_json::from_str(&status).expect("status is valid JSON");
        assert!(value["running"].is_boolean(), "running field present");
        assert!(value["backends"].is_array(), "backends is an array");
        assert!(value["cache"].is_object(), "cache object present");
        assert!(
            value["p2p_enabled"].is_boolean(),
            "p2p_enabled field present"
        );
    }

    #[tokio::test]
    async fn list_dir_lists_root_children() {
        let (_dir, _files, node) =
            node_with_files(&[("alpha.txt", b"aaa"), ("beta.bin", b"bbb")]).await;
        let entries = node
            .list_dir(NODE_MOUNT.to_owned())
            .await
            .expect("listing succeeds");
        let names: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();
        assert!(
            names.contains(&"alpha.txt"),
            "alpha.txt in listing: {names:?}"
        );
        assert!(
            names.contains(&"beta.bin"),
            "beta.bin in listing: {names:?}"
        );
        let alpha = entries
            .iter()
            .find(|e| e.name == "alpha.txt")
            .expect("alpha entry present");
        assert!(!alpha.is_dir, "file is not a dir");
    }

    #[tokio::test]
    async fn list_dir_marks_directories() {
        let (_dir, files_dir, node) = node_with_files(&[]).await;
        std::fs::create_dir(files_dir.join("subdir")).unwrap();
        let entries = node
            .list_dir(NODE_MOUNT.to_owned())
            .await
            .expect("listing succeeds");
        let subdir = entries
            .iter()
            .find(|e| e.name == "subdir")
            .expect("subdir in listing");
        assert!(subdir.is_dir, "subdir marked as directory");
    }

    #[tokio::test]
    async fn list_dir_accepts_leading_slash_path() {
        // Mobile callers (the iOS File Provider) pass leading-slash VFS paths
        // like "/local". The bridge normalises them to match the relative mount
        // prefix, so this must list the backend root, not fall through to the
        // empty neutral root.
        let (_dir, _files, node) = node_with_files(&[("a.txt", b"a")]).await;
        let entries = node
            .list_dir(format!("/{NODE_MOUNT}"))
            .await
            .expect("leading-slash path lists");
        assert!(
            entries.iter().any(|e| e.name == "a.txt"),
            "root file listed: {entries:?}"
        );
    }

    #[tokio::test]
    async fn read_file_returns_contents() {
        let (_dir, _files, node) = node_with_files(&[("doc.txt", b"hello cascade")]).await;
        let bytes = node
            .read_file(format!("{NODE_MOUNT}/doc.txt"))
            .await
            .expect("read succeeds");
        assert_eq!(bytes, b"hello cascade");
    }

    #[tokio::test]
    async fn read_file_missing_is_read_error() {
        let (_dir, _files, node) = node_with_files(&[]).await;
        let err = node
            .read_file(format!("{NODE_MOUNT}/nope.txt"))
            .await
            .expect_err("missing file errors");
        assert!(
            matches!(err, CascadeError::Read { .. }),
            "Read variant: {err:?}"
        );
    }

    #[tokio::test]
    async fn pin_and_unpin_round_trip() {
        let (_dir, _files, node) = node_with_files(&[("doc.txt", b"x")]).await;
        node.pin(format!("{NODE_MOUNT}/**"))
            .await
            .expect("pin succeeds");
        node.unpin(format!("{NODE_MOUNT}/**"))
            .await
            .expect("unpin succeeds");
    }

    /// mkdir -> list -> upload -> read -> rename -> delete round-trip over the
    /// local backend, exercising every new write verb end to end through the
    /// same VFS resolve path the mobile surfaces use.
    #[tokio::test]
    async fn write_round_trip_mkdir_upload_read_rename_delete() {
        let (_dir, _files, node) = node_with_files(&[]).await;

        // mkdir
        node.create_dir(format!("{NODE_MOUNT}/sub"))
            .await
            .expect("create_dir succeeds");
        let entries = node
            .list_dir(NODE_MOUNT.to_owned())
            .await
            .expect("list after mkdir");
        let subdir = entries
            .iter()
            .find(|e| e.name == "sub")
            .expect("sub listed");
        assert!(subdir.is_dir, "sub is a directory");

        // upload into sub
        node.upload(format!("{NODE_MOUNT}/sub/note.txt"), b"first".to_vec())
            .await
            .expect("upload succeeds");
        let bytes = node
            .read_file(format!("{NODE_MOUNT}/sub/note.txt"))
            .await
            .expect("read after upload");
        assert_eq!(bytes, b"first");

        // rename
        node.rename(
            format!("{NODE_MOUNT}/sub/note.txt"),
            format!("{NODE_MOUNT}/sub/renamed.txt"),
        )
        .await
        .expect("rename succeeds");
        let entries = node
            .list_dir(format!("{NODE_MOUNT}/sub"))
            .await
            .expect("list sub after rename");
        assert!(
            entries.iter().any(|e| e.name == "renamed.txt"),
            "renamed file present: {entries:?}"
        );
        assert!(
            !entries.iter().any(|e| e.name == "note.txt"),
            "old name gone: {entries:?}"
        );

        // delete
        node.delete(format!("{NODE_MOUNT}/sub/renamed.txt"))
            .await
            .expect("delete succeeds");
        let entries = node
            .list_dir(format!("{NODE_MOUNT}/sub"))
            .await
            .expect("list sub after delete");
        assert!(
            entries.iter().all(|e| e.name != "renamed.txt"),
            "file gone after delete: {entries:?}"
        );
    }

    /// Overwriting an existing file via `upload` should replace its contents,
    /// not error.
    #[tokio::test]
    async fn upload_overwrites_existing_file() {
        let (_dir, _files, node) = node_with_files(&[("doc.txt", b"old")]).await;
        node.upload(format!("{NODE_MOUNT}/doc.txt"), b"new".to_vec())
            .await
            .expect("overwrite upload succeeds");
        let bytes = node
            .read_file(format!("{NODE_MOUNT}/doc.txt"))
            .await
            .expect("read after overwrite");
        assert_eq!(bytes, b"new");
    }

    #[tokio::test]
    async fn delete_missing_is_write_error() {
        let (_dir, _files, node) = node_with_files(&[]).await;
        let err = node
            .delete(format!("{NODE_MOUNT}/nope.txt"))
            .await
            .expect_err("delete missing errors");
        assert!(
            matches!(err, CascadeError::Write { .. }),
            "Write variant: {err:?}"
        );
    }

    #[tokio::test]
    async fn create_dir_accepts_leading_slash_path() {
        let (_dir, _files, node) = node_with_files(&[]).await;
        node.create_dir(format!("/{NODE_MOUNT}/d"))
            .await
            .expect("leading-slash create_dir succeeds");
        let entries = node
            .list_dir(NODE_MOUNT.to_owned())
            .await
            .expect("list after create_dir");
        assert!(
            entries.iter().any(|e| e.name == "d"),
            "dir listed: {entries:?}"
        );
    }
}
