#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::string_slice
    )
)]
//! P2P-only storage backend.
//!
//! Unlike `cascade-backend-{gdrive,s3,local}`, this backend has no cloud
//! source of truth. Files live as content-addressed blocks in the local
//! P2P block store; folder metadata lives in a `SQLite` index. The full
//! mesh is reconstituted from peers — Syncthing-style — when peer
//! synchronisation is enabled (Phase 3).
//!
//! For now (Phase 2) the backend is functional as a local-only,
//! deduplicating content-addressed store. The same file uploaded twice
//! costs blocks once. Peer sync is a follow-up that wires the existing
//! `cascade_p2p::BepMessage` machinery onto this index.
//!
//! ## LAN discovery
//!
//! UDP-multicast LAN discovery is opt-in via `enable_discovery = true`
//! in the per-backend TOML. When enabled (and a `listen_addr` is set),
//! the backend periodically broadcasts its device ID and listening port
//! on the discovery multicast group, and listens for announcements from
//! other devices. Discovered peers that are in the trusted set and not
//! already connected get an outbound BEP connection attempt. With
//! discovery disabled, peer connectivity relies entirely on the static
//! `[[peers]]` config list.

pub mod index;
pub mod peer_relay;
pub mod sync;

use std::path::{Path, PathBuf};
use std::sync::Arc;

use anyhow::{Context, Result};
use async_trait::async_trait;
use cascade_engine::backend::Backend;
use cascade_engine::types::{Change, Cursor, FileEntry, FileId, ItemId, Quota};
use cascade_p2p::block::{BlockHash, split_data};
use cascade_p2p::candidate::{Candidate, CandidateKind};
use cascade_p2p::discovery::{Discovery, DiscoveryService, GossipDiscovery, LanDiscovery};
use cascade_p2p::identity::DeviceIdentity;
use cascade_p2p::protocol::Version;
use cascade_p2p::store::BlockStore;
use tokio::io::{AsyncReadExt, AsyncWriteExt};

use crate::index::{FolderIndex, IndexEntry};
use crate::sync::SyncEngine;

/// Poll interval reported to the engine.
///
/// The P2P backend receives updates via `IndexUpdate` push, but the sync
/// runner only surfaces new entries into the presenter on its next
/// poll. We keep the interval short (1 s) so peer-pushed files appear
/// in WebDAV/FUSE listings without user-visible lag.
const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_secs(1);

/// Default ceiling on the number of concurrent relay sessions this node
/// will bridge when volunteering as a peer relay.
///
/// A relay session bridges two peers, holding two `WebSocket` connections
/// and one byte-pipe task for its lifetime. Eight concurrent bridges is a
/// generous default for a personal mesh while bounding the memory, socket,
/// and bandwidth cost an `Open`/`FullCone` node takes on by volunteering.
/// Past the cap, new relay requests are rejected rather than silently
/// dropped (see [`crate::sync::SyncEngine`]).
pub const DEFAULT_MAX_RELAY_SESSIONS: u32 = 8;

/// Default ceiling on aggregate relay throughput, in bytes per second,
/// summed across every active relay session this node bridges.
///
/// Ten mebibytes per second keeps a volunteer useful for block exchange
/// without letting relayed traffic saturate a typical residential uplink.
/// The cap is named rather than a bare literal so the budget is visible
/// and tunable in one place.
pub const DEFAULT_MAX_RELAY_BANDWIDTH_BYTES_PER_SEC: u64 = 10 * 1024 * 1024;

/// Policy controlling whether this node volunteers as a peer relay.
///
/// A node only advertises itself as a relay candidate when its detected
/// `NAT` type is `Open` or `FullCone` — a node behind a restrictive `NAT`
/// cannot usefully relay. This policy gates that advertisement on the
/// operator's intent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RelayVolunteer {
    /// Never volunteer as a relay, regardless of `NAT` type.
    Off,
    /// Volunteer only to peers explicitly configured to receive the offer.
    /// Reserved for a future per-peer allow-list; today it behaves like
    /// `Auto` restricted to the trusted set, which is the same population
    /// `Auto` already targets.
    Explicit,
    /// Volunteer automatically to every trusted peer sharing a folder,
    /// provided the `NAT` type permits it. The default.
    #[default]
    Auto,
}

/// Statically-configured peer entry.
///
/// The address is stored as a `host:port` string and re-resolved on
/// every reconnect attempt. This is what we want for container DNS:
/// the peer may not be resolvable at startup (it hasn't booted yet)
/// but becomes resolvable seconds later.
///
/// `name` is an optional human-readable label seeded into the sync
/// engine's `device_id → friendly name` map at startup. Conflict copies
/// generated by this peer prefer the friendly name over the opaque
/// short device id when persisting the losing side.
#[derive(Debug, Clone)]
pub struct ConfiguredPeer {
    pub device_id: String,
    pub address: String,
    pub name: Option<String>,
}

/// Configuration for a P2P backend instance.
#[derive(Debug)]
pub struct P2pBackendConfig {
    pub instance_id: String,
    pub display_name: String,
    pub index_path: PathBuf,
    pub block_store_root: PathBuf,
    /// Directory used for the device identity certificate.
    pub identity_dir: PathBuf,
    /// Folder ID exchanged with peers. Defaults to `instance_id`.
    pub folder_id: String,
    /// If set, the backend starts a BEP listener on this address when
    /// opened. `None` disables the listener (the backend can still
    /// dial out to known peers).
    pub listen_addr: Option<std::net::SocketAddr>,
    /// Static peer list — connection attempts run in the background.
    pub peers: Vec<ConfiguredPeer>,
    /// Enable UDP-multicast LAN discovery. Default `false` so the
    /// existing static-peer story is opt-out.
    pub enable_discovery: bool,
    /// Friendly name for the LOCAL device. Used by the sync engine when
    /// stamping conflict-copy paths so the displaced side is identified
    /// by a human-readable label (e.g. `report.conflict-work-laptop-…`)
    /// rather than the opaque first eight characters of the device id.
    /// `None` falls back to the short device id.
    pub device_name: Option<String>,
    /// Enable WAN peer gossip. When `true`, the backend broadcasts a
    /// snapshot of its known peer list to every connected peer every
    /// 60 seconds via a `BepMessage::Gossip` frame, and merges any
    /// gossip frames it receives into its own peer book.
    ///
    /// The peers carried in gossip are the ones the local peer book
    /// has learned about through past connections (static peer config
    /// and inbound connections that completed the TLS handshake).
    /// External NAT-derived addresses are not yet folded in — that is
    /// a follow-up that needs the NAT-detection signal to thread
    /// through into the peer book.
    ///
    /// The local [`SyncEngine`] maintains its `PeerBook` unconditionally
    /// (useful for future relay-candidate selection and NAT-traversal
    /// hints); this flag only controls whether gossip frames flow.
    pub enable_wan_gossip: bool,
    /// STUN servers used for NAT type detection at startup. Empty means
    /// no NAT detection runs. Each entry is a `host:port` string; the
    /// first server that responds wins.
    pub stun_servers: Vec<String>,
    /// Known relay endpoints, in preference order. Fed into
    /// [`cascade_p2p::decide_connectivity`] as the relay pool when the
    /// strategy table calls for relayed transport. Empty disables the
    /// relay strategy — pairs that would otherwise relay fall through
    /// to a best-effort hole punch.
    pub relay_endpoints: Vec<std::net::SocketAddr>,
    /// Shared secret authenticating this device against the relay
    /// pool. `None` means the relay path is provisioned but unusable;
    /// `decide_connectivity` may still pick `Relay` but the relay
    /// strategy will skip the dial without a secret.
    /// The 32-byte width matches the cascade relay's HMAC key length.
    pub relay_shared_secret: Option<[u8; 32]>,
    /// Hole-punching opt-out. When `false`, [`cascade_p2p::decide_connectivity`]
    /// is still consulted but the chosen `HolePunch` strategy is
    /// downgraded to direct-or-relay before any UDP burst is emitted.
    /// Defaults to `true` so production deployments get the full path
    /// out of the box.
    pub enable_hole_punch: bool,
    /// Whether this node volunteers as a peer relay. When not
    /// [`RelayVolunteer::Off`] and the detected `NAT` type is `Open` or
    /// `FullCone`, the node advertises itself as a relay candidate to
    /// trusted peers it shares a folder with via a
    /// [`cascade_p2p::protocol::BepMessage::RelayOffer`]. Defaults to
    /// [`RelayVolunteer::Auto`].
    pub relay_volunteer: RelayVolunteer,
    /// Ceiling on concurrent relay sessions this node bridges while
    /// volunteering. New requests past the cap are rejected rather than
    /// silently dropped. Defaults to [`DEFAULT_MAX_RELAY_SESSIONS`].
    pub max_relay_sessions: u32,
    /// Ceiling on aggregate relay throughput, in bytes per second, across
    /// every active relay session. Defaults to
    /// [`DEFAULT_MAX_RELAY_BANDWIDTH_BYTES_PER_SEC`].
    pub max_relay_bandwidth: u64,
}

impl Default for P2pBackendConfig {
    fn default() -> Self {
        Self {
            instance_id: String::new(),
            display_name: String::new(),
            index_path: PathBuf::new(),
            block_store_root: PathBuf::new(),
            identity_dir: PathBuf::new(),
            folder_id: String::new(),
            listen_addr: None,
            peers: Vec::new(),
            enable_discovery: false,
            device_name: None,
            enable_wan_gossip: false,
            stun_servers: Vec::new(),
            relay_endpoints: Vec::new(),
            relay_shared_secret: None,
            // Hole-punching is enabled by default — operators opt OUT by
            // setting `enable_hole_punch = false`, mirroring the way
            // `enable_discovery` and `enable_wan_gossip` are opt-IN flags
            // for behaviour with a real operational cost.
            enable_hole_punch: true,
            // Volunteering is on by default but gated on NAT type: only
            // `Open`/`FullCone` nodes ever actually advertise an offer, so
            // a default of `Auto` costs nothing on the restrictive nodes
            // that cannot relay anyway.
            relay_volunteer: RelayVolunteer::Auto,
            max_relay_sessions: DEFAULT_MAX_RELAY_SESSIONS,
            max_relay_bandwidth: DEFAULT_MAX_RELAY_BANDWIDTH_BYTES_PER_SEC,
        }
    }
}

/// A P2P backend instance.
pub struct P2pBackend {
    cfg: P2pBackendConfig,
    index: Arc<FolderIndex>,
    blocks: Arc<BlockStore>,
    sync: SyncEngine,
    /// Signals all spawned background tasks to exit. Set to `true` on
    /// drop. Tasks select on `cancel.changed()` and break their loops
    /// when they observe the flag flip.
    cancel: tokio::sync::watch::Sender<bool>,
}

impl std::fmt::Debug for P2pBackend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("P2pBackend")
            .field("id", &self.cfg.instance_id)
            .field("display_name", &self.cfg.display_name)
            .finish_non_exhaustive()
    }
}

impl Drop for P2pBackend {
    fn drop(&mut self) {
        // Best-effort: signal every background task to exit. If all
        // receivers have already been dropped (no tasks running), the
        // send is a no-op error we intentionally ignore.
        let _ = self.cancel.send(true);
    }
}

impl P2pBackend {
    /// Open or create a P2P backend at the given index + block store
    /// paths. Synchronous: filesystem setup happens up-front so this
    /// is callable from within a tokio runtime worker thread without
    /// nested-runtime panics. If `cfg.listen_addr` is set, a BEP
    /// listener is spawned (via `tokio::spawn`); every configured peer
    /// gets a background reconnect task.
    ///
    /// All spawned background tasks share a `tokio::sync::watch`
    /// channel; when the returned `P2pBackend` is dropped, every task
    /// observes the cancellation flag and exits cleanly. This matters
    /// in tests and when a backend is removed at runtime — without it
    /// the listener, the per-peer reconnect loops, and the LAN
    /// discovery loops would leak past the backend's lifetime,
    /// keeping `Arc<FolderIndex>` and `Arc<BlockStore>` alive
    /// indefinitely.
    pub fn open(cfg: P2pBackendConfig) -> Result<Self> {
        let index = Arc::new(FolderIndex::open(&cfg.index_path)?);
        let blocks = Arc::new(BlockStore::new(&cfg.block_store_root).context("open block store")?);
        let identity = DeviceIdentity::load_or_generate(&cfg.identity_dir)
            .context("loading P2P backend identity")?;
        let sync = SyncEngine::new(
            cfg.folder_id.clone(),
            index.clone(),
            blocks.clone(),
            identity,
        )
        .with_local_device_name(cfg.device_name.clone())
        .with_relay_endpoints(cfg.relay_endpoints.clone())
        .with_relay_shared_secret(cfg.relay_shared_secret)
        .with_hole_punch_enabled(cfg.enable_hole_punch)
        .with_relay_volunteer(cfg.relay_volunteer)
        .with_relay_session_caps(cfg.max_relay_sessions, cfg.max_relay_bandwidth);

        // Cancellation channel for all background tasks. `false` =
        // run, `true` = stop. The `Sender` lives on `P2pBackend`; its
        // `Drop` flips the flag.
        let (cancel, _) = tokio::sync::watch::channel(false);

        // Trust + reconnect tasks need a runtime — spawn them on the
        // current handle. The caller must be inside a tokio context.
        let sync_for_listener = sync.clone();
        let cfg_listen_addr = cfg.listen_addr;
        let cfg_instance_id = cfg.instance_id.clone();
        let cfg_peers = cfg.peers.clone();
        let cfg_enable_discovery = cfg.enable_discovery;
        let cfg_enable_wan_gossip = cfg.enable_wan_gossip;
        let cfg_stun_servers = cfg.stun_servers.clone();
        let bootstrap_cancel = cancel.subscribe();
        let cancel_for_children = cancel.clone();
        tokio::spawn(async move {
            for peer in &cfg_peers {
                sync_for_listener.trust(peer.device_id.clone()).await;
            }
            // Seed the friendly-name map from the static peer list. Any
            // peer without a configured `name` is skipped — peers are
            // not auto-named, the absence is preserved so a later
            // protocol extension can fill them in without colliding.
            let name_entries: Vec<(String, String)> = cfg_peers
                .iter()
                .filter_map(|p| p.name.clone().map(|n| (p.device_id.clone(), n)))
                .collect();
            if !name_entries.is_empty() {
                sync_for_listener.seed_peer_names(name_entries).await;
            }

            // Wire WAN gossip: every minute, broadcast a snapshot of
            // the local peer book to every connected peer via the
            // `BepMessage::Gossip` frame. Receivers merge the snapshot
            // into their own peer book so devices that are not directly
            // configured for each other still learn about one another
            // transitively through any shared peer.
            //
            // The gossip task observes the same cancellation watch as
            // the rest of the children so it exits cleanly when the
            // backend is dropped.
            if cfg_enable_wan_gossip {
                tracing::info!(
                    target: "cascade::backend::p2p",
                    instance = %cfg_instance_id,
                    "WAN gossip enabled — broadcasting peer-book snapshot every 60s"
                );
                let gossip_sync = sync_for_listener.clone();
                let mut gossip_cancel = cancel_for_children.subscribe();
                tokio::spawn(async move {
                    loop {
                        tokio::select! {
                            () = tokio::time::sleep(std::time::Duration::from_mins(1)) => {
                                gossip_sync.broadcast_gossip().await;
                            }
                            res = gossip_cancel.changed() => {
                                if res.is_err() || *gossip_cancel.borrow() {
                                    return;
                                }
                            }
                        }
                    }
                });
            }

            // NAT detection runs in the background so a slow STUN
            // round-trip doesn't delay listener bind-up. The result is
            // published onto the engine (`SyncEngine::set_local_nat_type`)
            // and read by `connect_to_with_strategy` whenever a peer
            // connection attempt consults `decide_connectivity`. Local
            // NAT type stays `Unknown` until the task completes — that's
            // the conservative reading: the table routes Unknown
            // through Relay (with a punch fallback) until the real
            // classification arrives.
            if !cfg_stun_servers.is_empty() {
                let nat_sync = sync_for_listener.clone();
                let nat_instance = cfg_instance_id.clone();
                let nat_servers = cfg_stun_servers.clone();
                tokio::spawn(async move {
                    detect_nat_and_publish(&nat_instance, &nat_servers, &nat_sync).await;
                });
            }

            // Bind the listener first so subsequent announce loops can
            // advertise the actual bound port (important when
            // `listen_addr` uses port 0 — peers receiving a port-0
            // announcement would be unable to connect back).
            let bound_port = match cfg_listen_addr {
                Some(addr) => {
                    let listener_cancel = cancel_for_children.subscribe();
                    match sync_for_listener
                        .start_listener(addr, listener_cancel)
                        .await
                    {
                        Ok((bound, _handle)) => {
                            tracing::info!(
                                target: "cascade::backend::p2p",
                                "P2P backend `{}` listening on {bound} as device {}",
                                cfg_instance_id,
                                sync_for_listener.device_id(),
                            );
                            Some(bound.port())
                        }
                        Err(e) => {
                            tracing::error!(
                                target: "cascade::backend::p2p",
                                "P2P backend `{}` failed to listen on {addr}: {e:#}",
                                cfg_instance_id,
                            );
                            None
                        }
                    }
                }
                None => None,
            };

            // If we were cancelled while starting the listener, bail
            // out before spawning any further children.
            if *bootstrap_cancel.borrow() {
                return;
            }

            for peer in cfg_peers {
                let sync_clone = sync_for_listener.clone();
                let peer_cancel = cancel_for_children.subscribe();
                tokio::spawn(async move {
                    keep_peer_connected(sync_clone, peer, peer_cancel).await;
                });
            }

            // Compose the discovery sources into a single service. The
            // two sources registered here are exactly the two the backend
            // already ran: LAN multicast behind `enable_discovery`, and
            // introducer gossip behind `enable_wan_gossip`. The service
            // is the structural home for discovery — the loops below feed
            // their I/O through the registered `LanDiscovery` source so
            // the wire behaviour is unchanged.
            let mut discovery = DiscoveryService::new();
            if cfg_enable_wan_gossip {
                discovery.register(Box::new(GossipDiscovery::new(
                    sync_for_listener.peer_book().clone(),
                )));
            }
            let lan_source = (cfg_enable_discovery && bound_port.is_some()).then(LanDiscovery::new);
            if let Some(lan) = lan_source {
                discovery.register(Box::new(lan));
            }
            tracing::debug!(
                target: "cascade::backend::p2p",
                instance = %cfg_instance_id,
                sources = discovery.len(),
                "discovery service composed",
            );

            if let (Some(lan), Some(listen_port)) = (lan_source, bound_port) {
                let announce_sync = sync_for_listener.clone();
                let announce_cancel = cancel_for_children.subscribe();
                tokio::spawn(async move {
                    discovery_announce_loop(lan, announce_sync, listen_port, announce_cancel).await;
                });
                let listen_sync = sync_for_listener.clone();
                let listen_cancel = cancel_for_children.subscribe();
                tokio::spawn(async move {
                    discovery_listen_loop(lan, listen_sync, listen_cancel).await;
                });
            }
        });

        Ok(Self {
            cfg,
            index,
            blocks,
            sync,
            cancel,
        })
    }

    /// Access the sync engine — used to start a listener and add peers.
    #[must_use]
    pub const fn sync(&self) -> &SyncEngine {
        &self.sync
    }

    /// Convert a `FolderIndex` row into a `FileEntry` keyed under this
    /// backend's instance ID. Root entries (those with no `/` in `path`)
    /// have `parent_id = "root"`; nested entries point at their parent
    /// path as the native ID.
    fn entry_to_file(&self, entry: &IndexEntry) -> FileEntry {
        let (parent_native, name) = match entry.path.rsplit_once('/') {
            Some((parent, name)) => (parent.to_string(), name.to_string()),
            None => ("root".to_string(), entry.path.clone()),
        };
        let modified = chrono::DateTime::from_timestamp(entry.modified, 0);
        FileEntry {
            id: ItemId::new(&self.cfg.instance_id, &entry.path),
            parent_id: ItemId::new(&self.cfg.instance_id, &parent_native),
            name,
            is_dir: entry.is_dir,
            size: if entry.is_dir { None } else { Some(entry.size) },
            mod_time: modified,
            mime_type: None,
            hash: None,
        }
    }

    /// Synthetic root entry (no real index row).
    fn root_entry(&self) -> FileEntry {
        FileEntry::dir(
            ItemId::new(&self.cfg.instance_id, "root"),
            ItemId::new(&self.cfg.instance_id, "root"),
            "P2P".to_string(),
        )
    }
}

#[async_trait]
impl Backend for P2pBackend {
    fn id(&self) -> &str {
        &self.cfg.instance_id
    }

    fn display_name(&self) -> &str {
        &self.cfg.display_name
    }

    async fn quota(&self) -> Result<Option<Quota>> {
        // No accounting yet — peer storage is opaque.
        Ok(None)
    }

    async fn changes(&self, cursor: Option<&Cursor>) -> Result<(Vec<Change>, Cursor)> {
        let since: i64 = cursor.and_then(|c| c.0.parse().ok()).unwrap_or(0);
        let entries = self.index.entries_since(since)?;
        let mut changes = Vec::with_capacity(entries.len());
        for entry in &entries {
            let file = self.entry_to_file(entry);
            if entry.deleted {
                changes.push(Change::Deleted(file));
            } else {
                changes.push(Change::Created(file));
            }
        }
        let new_cursor = self.index.max_version()?;
        Ok((changes, Cursor(new_cursor.to_string())))
    }

    async fn metadata(&self, path: &Path) -> Result<FileEntry> {
        let path_str = path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-utf8 path"))?
            .trim_start_matches('/')
            .to_string();
        if path_str.is_empty() {
            return Ok(self.root_entry());
        }
        let entry = self
            .index
            .get(&path_str)?
            .ok_or_else(|| anyhow::anyhow!("not found: {path_str}"))?;
        if entry.deleted {
            anyhow::bail!("not found (deleted): {path_str}");
        }
        Ok(self.entry_to_file(&entry))
    }

    async fn download(
        &self,
        file: &FileEntry,
        writer: &mut (dyn tokio::io::AsyncWrite + Unpin + Send),
    ) -> Result<()> {
        let native = file.id.native_id();
        let entry = self
            .index
            .get(native)?
            .ok_or_else(|| anyhow::anyhow!("not in index: {native}"))?;
        let block_size = cascade_p2p::block::block_size_for_file(entry.size);
        // Block hashes are stored as concatenated 32-byte values.
        for (idx, chunk) in entry.block_hashes.chunks(32).enumerate() {
            let mut h = [0u8; 32];
            h.copy_from_slice(chunk);
            let hash = BlockHash(h);
            let data = if let Some(data) = self.blocks.get_block(&hash).await? {
                data
            } else {
                let fetched = self
                    .sync
                    .fetch_block(native, idx, block_size, h)
                    .await
                    .ok_or_else(|| anyhow::anyhow!("block {hash} missing and no peer had it"))?;
                // Cache the fetched block locally so future reads hit
                // the store without round-tripping the network.
                self.blocks.store_block(&hash, &fetched).await?;
                fetched
            };
            writer.write_all(&data).await?;
        }
        writer.flush().await?;
        Ok(())
    }

    /// Range read that fetches only the content-addressed blocks
    /// overlapping `[offset, offset + length)`.
    ///
    /// Rather than reconstructing the whole file (as the default impl
    /// does via [`Backend::download`]), this computes the span of blocks
    /// that cover the requested window, fetches just those blocks (local
    /// store first, then peers — caching anything pulled over the wire,
    /// exactly as `download` does), assembles them into a contiguous
    /// buffer aligned to the first block's file offset, then slices out
    /// the exact `[offset, offset + length)` window.
    ///
    /// Contract: the result may be shorter than `length` at end-of-file,
    /// is empty when `offset` is at or past the reconstructed size, and
    /// never panics on out-of-range offset/length.
    async fn read_range(&self, file: &FileEntry, offset: u64, length: u32) -> Result<Vec<u8>> {
        // A zero-length request reads nothing regardless of offset.
        if length == 0 {
            return Ok(Vec::new());
        }

        let native = file.id.native_id();
        let entry = self
            .index
            .get(native)?
            .ok_or_else(|| anyhow::anyhow!("not in index: {native}"))?;

        // Offset at or past the reconstructed size yields no bytes.
        if offset >= entry.size {
            return Ok(Vec::new());
        }

        let block_size = cascade_p2p::block::block_size_for_file(entry.size);
        let block_size_u64 = u64::from(block_size);
        // A zero block size would make the index arithmetic below
        // undefined; treat it as a malformed entry rather than dividing
        // by zero.
        if block_size_u64 == 0 {
            anyhow::bail!("block size of zero for {native}");
        }

        // Block hashes are stored as concatenated 32-byte values.
        let block_count = entry.block_hashes.len() / 32;
        if block_count == 0 {
            return Ok(Vec::new());
        }
        // The last addressable block index. Used to clamp the computed
        // `last_block` so a `length` running past EOF never references a
        // block that does not exist.
        let max_block = block_count.saturating_sub(1);

        // The window's inclusive last byte. `length > 0` and
        // `offset < entry.size` are both already established, so the
        // subtraction cannot wrap.
        let last_byte = offset.saturating_add(u64::from(length)).saturating_sub(1);

        let first_block_u64 = offset / block_size_u64;
        let last_block_u64 = last_byte / block_size_u64;
        let first_block = usize::try_from(first_block_u64)
            .map_err(|_| anyhow::anyhow!("first block index overflow"))?;
        let last_block = usize::try_from(last_block_u64)
            .map_err(|_| anyhow::anyhow!("last block index overflow"))?
            .min(max_block);

        // Byte offset in the file where the assembled buffer begins —
        // the start of the first covering block.
        let assembled_start = first_block_u64.saturating_mul(block_size_u64);

        // Fetch and concatenate only the covering blocks.
        let mut assembled: Vec<u8> = Vec::new();
        for idx in first_block..=last_block {
            let hash_start = idx.saturating_mul(32);
            let hash_end = hash_start.saturating_add(32);
            let chunk = entry
                .block_hashes
                .get(hash_start..hash_end)
                .ok_or_else(|| anyhow::anyhow!("block hash {idx} out of range for {native}"))?;
            let mut h = [0u8; 32];
            h.copy_from_slice(chunk);
            let hash = BlockHash(h);
            let data = if let Some(data) = self.blocks.get_block(&hash).await? {
                data
            } else {
                let fetched = self
                    .sync
                    .fetch_block(native, idx, block_size, h)
                    .await
                    .ok_or_else(|| anyhow::anyhow!("block {hash} missing and no peer had it"))?;
                // Cache the fetched block locally so future reads hit
                // the store without round-tripping the network.
                self.blocks.store_block(&hash, &fetched).await?;
                fetched
            };
            assembled.extend_from_slice(&data);
        }

        // Translate the absolute window into an offset within the
        // assembled buffer, clamping the end to what was actually
        // reconstructed (the final block may be short).
        let rel_start_u64 = offset.saturating_sub(assembled_start);
        let rel_start = usize::try_from(rel_start_u64)
            .map_err(|_| anyhow::anyhow!("relative offset overflow"))?
            .min(assembled.len());
        let want = usize::try_from(length).unwrap_or(usize::MAX);
        let rel_end = rel_start.saturating_add(want).min(assembled.len());
        Ok(assembled
            .get(rel_start..rel_end)
            .unwrap_or_default()
            .to_vec())
    }

    async fn upload(
        &self,
        path: &Path,
        reader: &mut (dyn tokio::io::AsyncRead + Unpin + Send),
        parent_id: &FileId,
    ) -> Result<FileEntry> {
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| anyhow::anyhow!("invalid filename"))?;
        let parent_native = parent_id.native_id();
        let path_str = if parent_native == "root" || parent_native.is_empty() {
            name.to_string()
        } else {
            format!("{parent_native}/{name}")
        };

        let mut data = Vec::new();
        reader.read_to_end(&mut data).await?;
        let size = data.len() as u64;

        let blocks_info = split_data(&data);
        let block_size = blocks_info.block_size as usize;
        let mut hash_blob = Vec::with_capacity(blocks_info.blocks.len() * 32);
        for (idx, hash) in blocks_info.blocks.iter().enumerate() {
            let start = idx * block_size;
            let end = (start + block_size).min(data.len());
            #[allow(clippy::indexing_slicing)] // bounds derived from split_data
            let slice = &data[start..end];
            self.blocks.store_block(hash, slice).await?;
            hash_blob.extend_from_slice(&hash.0);
        }

        // Bump the local device's version-vector counter so peers can
        // tell this write apart from any concurrent edit. The existing
        // counter (if any) is taken from the prior row.
        let mut version = Version {
            counters: self
                .index
                .get(&path_str)?
                .map(|e| e.version)
                .unwrap_or_default(),
        };
        version.bump(self.sync.device_short_id());

        let entry = IndexEntry {
            path: path_str.clone(),
            is_dir: false,
            size,
            modified: chrono::Utc::now().timestamp(),
            block_hashes: hash_blob,
            deleted: false,
            row_version: 0,
            version: version.counters,
        };
        self.index.upsert(&entry)?;
        self.sync.broadcast_update(&entry).await;
        Ok(self.entry_to_file(&entry))
    }

    async fn update(
        &self,
        file_id: &FileId,
        reader: &mut (dyn tokio::io::AsyncRead + Unpin + Send),
    ) -> Result<FileEntry> {
        let native = file_id.native_id();
        let existing = self
            .index
            .get(native)?
            .ok_or_else(|| anyhow::anyhow!("not in index: {native}"))?;
        let parent = match native.rsplit_once('/') {
            Some((parent, _)) => format!("{}:{parent}", self.cfg.instance_id),
            None => format!("{}:root", self.cfg.instance_id),
        };
        // Re-upload using the same path.
        self.upload(Path::new(&existing.path), reader, &FileId(parent))
            .await
    }

    async fn create_dir(&self, path: &Path) -> Result<FileEntry> {
        let path_str = path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-utf8 path"))?
            .trim_start_matches('/')
            .to_string();
        // Directory rows carry a version vector for symmetry with file
        // rows even though BEP never propagates directories — peers
        // infer them from the parent path of each file.
        let mut version = Version {
            counters: self
                .index
                .get(&path_str)?
                .map(|e| e.version)
                .unwrap_or_default(),
        };
        version.bump(self.sync.device_short_id());
        let entry = IndexEntry {
            path: path_str,
            is_dir: true,
            size: 0,
            modified: chrono::Utc::now().timestamp(),
            block_hashes: Vec::new(),
            deleted: false,
            row_version: 0,
            version: version.counters,
        };
        self.index.upsert(&entry)?;
        Ok(self.entry_to_file(&entry))
    }

    async fn delete(&self, file: &FileEntry) -> Result<()> {
        let native = file.id.native_id();
        // Bump the local device's counter so peers see this tombstone
        // as causally newer than whatever they last received for this
        // path. Reading the existing row gives us the prior vector to
        // extend rather than overwrite.
        let existing = self
            .index
            .get(native)?
            .ok_or_else(|| anyhow::anyhow!("not in index: {native}"))?;
        let mut version = Version {
            counters: existing.version,
        };
        version.bump(self.sync.device_short_id());
        let tombstone = IndexEntry {
            path: existing.path,
            is_dir: existing.is_dir,
            size: 0,
            modified: chrono::Utc::now().timestamp(),
            block_hashes: vec![],
            deleted: true,
            row_version: 0,
            version: version.counters,
        };
        self.index.upsert(&tombstone)?;
        // Broadcast the tombstone so peers can mirror the delete.
        self.sync.broadcast_update(&tombstone).await;
        Ok(())
    }

    async fn move_entry(&self, src: &Path, dst: &Path) -> Result<FileEntry> {
        let src_str = src
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-utf8 src path"))?
            .trim_start_matches('/');
        let dst_str = dst
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-utf8 dst path"))?
            .trim_start_matches('/');
        let existing = self
            .index
            .get(src_str)?
            .ok_or_else(|| anyhow::anyhow!("not in index: {src_str}"))?;
        let now = chrono::Utc::now().timestamp();
        let short_id = self.sync.device_short_id();

        // The destination row inherits the source's vector with the
        // local counter bumped, merged with any prior destination
        // vector so we don't accidentally regress against a peer.
        let mut dst_version = Version {
            counters: existing.version.clone(),
        };
        if let Some(existing_dst) = self.index.get(dst_str)? {
            dst_version.merge(&Version {
                counters: existing_dst.version,
            });
        }
        dst_version.bump(short_id);
        let new_entry = IndexEntry {
            path: dst_str.to_string(),
            is_dir: existing.is_dir,
            size: existing.size,
            modified: now,
            block_hashes: existing.block_hashes,
            deleted: false,
            row_version: 0,
            version: dst_version.counters,
        };
        self.index.upsert(&new_entry)?;

        // The source row becomes a tombstone with its own counter
        // bumped so peers see the delete as causally newer than the
        // row they last received.
        let mut src_version = Version {
            counters: existing.version,
        };
        src_version.bump(short_id);
        let tombstone = IndexEntry {
            path: src_str.to_string(),
            is_dir: false,
            size: 0,
            modified: now,
            block_hashes: vec![],
            deleted: true,
            row_version: 0,
            version: src_version.counters,
        };
        self.index.upsert(&tombstone)?;
        Ok(self.entry_to_file(&new_entry))
    }

    async fn list_children(&self, parent_native_id: &str) -> Result<Vec<FileEntry>> {
        let parent = if parent_native_id == "root" {
            ""
        } else {
            parent_native_id
        };
        let rows = self.index.list_children(parent)?;
        Ok(rows.iter().map(|e| self.entry_to_file(e)).collect())
    }

    async fn poll_interval(&self) -> Option<std::time::Duration> {
        // The local index is updated synchronously and there is no remote
        // source to poll (peer sync pushes IndexUpdate messages when
        // wired). 60s is a sensible default so changes() is still called
        // periodically to flush queued peer changes.
        Some(POLL_INTERVAL)
    }
}

/// Retry loop: try to keep an outbound BEP connection to `peer` up.
///
/// `connect_to` returns immediately after spawning the session; if the
/// session ends (e.g. the peer crashed or the network blipped), our
/// peer table loses the entry and we should try again. The 5s back-off
/// is enough to avoid busy-looping on a sustained outage and short
/// enough to recover quickly from a transient one.
///
/// DNS resolution happens here, not at config-parse time, so a peer
/// hostname that isn't yet routable at startup (the typical Docker
/// case) becomes routable on the next tick.
///
/// Exits as soon as `cancel` flips to `true`.
async fn keep_peer_connected(
    sync: SyncEngine,
    peer: ConfiguredPeer,
    mut cancel: tokio::sync::watch::Receiver<bool>,
) {
    let peer_id = peer.device_id.clone();
    let peer_addr_raw = peer.address.clone();
    loop {
        if *cancel.borrow() {
            return;
        }
        let already = sync.has_peer(&peer_id).await;
        if !already {
            match resolve_first(&peer_addr_raw).await {
                Ok(addr) => {
                    if let Err(e) = sync
                        .connect_to(crate::sync::Peer {
                            device_id: peer.device_id.clone(),
                            address: addr,
                        })
                        .await
                    {
                        tracing::debug!(
                            target: "cascade::backend::p2p",
                            "peer {peer_id} not reachable at {addr}: {e:#}; retrying",
                        );
                    }
                }
                Err(e) => {
                    tracing::debug!(
                        target: "cascade::backend::p2p",
                        "peer {peer_id} address `{peer_addr_raw}` did not resolve: {e:#}; retrying",
                    );
                }
            }
        }
        tokio::select! {
            () = tokio::time::sleep(std::time::Duration::from_secs(5)) => {}
            res = cancel.changed() => {
                if res.is_err() || *cancel.borrow() {
                    return;
                }
            }
        }
    }
}

/// Detect the local `NAT` type via STUN and persist it on `sync`.
///
/// When two or more STUN servers are configured, runs the RFC 5780
/// two-server detection on a freshly bound UDP socket — that path
/// distinguishes the full taxonomy (`Open` / `FullCone` /
/// `RestrictedCone` / `PortRestrictedCone` / `Symmetric`) the
/// connectivity strategy table depends on. With a single server,
/// falls back to the single-server detection that only distinguishes
/// `Open` from `Symmetric` — better than nothing, but the table will
/// route most cases through `Relay` or best-effort punch. With no
/// servers, leaves the engine at `NatType::Unknown`.
///
/// Failures log at `warn` and leave the local NAT type unchanged
/// (default `NatType::Unknown` — conservative).
async fn detect_nat_and_publish(
    instance_id: &str,
    stun_servers: &[String],
    sync: &crate::sync::SyncEngine,
) {
    // Resolve `host:port` strings to socket addresses up-front so the
    // RFC 5780 path has concrete `primary`/`secondary` to work with.
    let resolved: Vec<std::net::SocketAddr> = {
        let mut out = Vec::with_capacity(stun_servers.len());
        for raw in stun_servers {
            match resolve_first(raw).await {
                Ok(addr) => out.push(addr),
                Err(e) => tracing::debug!(
                    target: "cascade::backend::p2p",
                    stun = %raw,
                    error = %e,
                    "could not resolve STUN server",
                ),
            }
        }
        out
    };

    if resolved.len() >= 2 {
        // RFC 5780 path. Need a bound UDP socket so the detection
        // reuses the same source for all four probes.
        let socket = match tokio::net::UdpSocket::bind("0.0.0.0:0").await {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!(
                    target: "cascade::backend::p2p",
                    instance = %instance_id,
                    error = %e,
                    "binding STUN socket failed; leaving local NAT type as Unknown",
                );
                return;
            }
        };
        let Some(primary) = resolved.first().copied() else {
            // Unreachable — `len() >= 2` implies at least one entry.
            // Logged at warn so a future refactor that violates the
            // invariant surfaces visibly rather than silently
            // skipping detection.
            tracing::warn!(
                target: "cascade::backend::p2p",
                instance = %instance_id,
                "RFC 5780 path entered with empty STUN list — leaving local NAT type as Unknown",
            );
            return;
        };
        let Some(secondary) = resolved.get(1).copied() else {
            tracing::warn!(
                target: "cascade::backend::p2p",
                instance = %instance_id,
                "RFC 5780 path entered without a secondary STUN server — leaving local NAT type as Unknown",
            );
            return;
        };
        let cfg = cascade_p2p::nat::NatDetectionConfig {
            primary,
            secondary,
            per_request_timeout: std::time::Duration::from_secs(3),
            retries: 2,
        };
        match cascade_p2p::nat::detect_nat_type_rfc5780(&socket, &cfg).await {
            Ok(outcome) => {
                tracing::info!(
                    target: "cascade::backend::p2p",
                    instance = %instance_id,
                    nat = ?outcome.nat_type(),
                    external = ?outcome.external_socket_addr(),
                    "RFC 5780 NAT type detected",
                );
                sync.set_local_nat_type(outcome.nat_type()).await;
                // Stash the external mapping so gather_local_candidates
                // can fold a ServerReflexive candidate into the
                // gossiped set. The single-server path below has no
                // way to extract this — `NatTraversal::detect_nat_type`
                // discards the XOR-MAPPED-ADDRESS — so only RFC 5780
                // populates it.
                sync.set_local_external_addr(outcome.external_socket_addr())
                    .await;
            }
            Err(e) => tracing::warn!(
                target: "cascade::backend::p2p",
                instance = %instance_id,
                error = %e,
                "RFC 5780 NAT detection failed; leaving local NAT type as Unknown",
            ),
        }
        return;
    }

    // Single-server path — only distinguishes Open from Symmetric.
    for stun in stun_servers {
        match cascade_p2p::nat::NatTraversal::detect_nat_type(stun).await {
            Ok(nat_type) => {
                tracing::info!(
                    target: "cascade::backend::p2p",
                    instance = %instance_id,
                    stun = %stun,
                    nat = ?nat_type,
                    "single-server NAT type detected",
                );
                sync.set_local_nat_type(nat_type).await;
                return;
            }
            Err(e) => {
                tracing::debug!(
                    target: "cascade::backend::p2p",
                    stun = %stun,
                    error = %e,
                    "NAT detection failed; trying next server",
                );
            }
        }
    }
}

/// Resolve `host:port` (or `addr:port`) to a single `SocketAddr`,
/// off-thread so we don't block the tokio runtime.
async fn resolve_first(raw: &str) -> Result<std::net::SocketAddr> {
    let owned = raw.to_string();
    let addrs = tokio::task::spawn_blocking(move || {
        std::net::ToSocketAddrs::to_socket_addrs(&owned).map(Iterator::collect::<Vec<_>>)
    })
    .await
    .context("DNS resolve task panicked")?
    .with_context(|| format!("resolving `{raw}`"))?;
    addrs
        .into_iter()
        .next()
        .with_context(|| format!("`{raw}` resolved to no records"))
}

/// Local preference for the single LAN host candidate this device
/// advertises. LAN announcements carry exactly one BEP listen port, so
/// there is no interface ranking to encode; the maximum value matches
/// the value [`LanDiscovery`] assigns to discovered LAN peers, keeping
/// the two sides symmetric.
const LAN_ANNOUNCE_LOCAL_PREFERENCE: u16 = u16::MAX;

/// Build the single host candidate carried in a LAN announcement. The
/// announcement wire shape conveys only the device ID and BEP listen
/// port; [`LanDiscovery::announce`] extracts the port from the
/// highest-priority host candidate, so the address IP is irrelevant and
/// the wildcard is used.
fn lan_announce_candidate(listen_port: u16) -> Candidate {
    let address = std::net::SocketAddr::from((std::net::Ipv4Addr::UNSPECIFIED, listen_port));
    Candidate::new(address, CandidateKind::Host, LAN_ANNOUNCE_LOCAL_PREFERENCE)
}

/// Periodically broadcast our presence on the LAN discovery multicast
/// group via the [`LanDiscovery`] source.
///
/// The announce itself is a blocking std-net call hopped onto
/// `spawn_blocking` inside [`LanDiscovery::announce`]; errors there are
/// logged and swallowed — discovery is best-effort.
///
/// Exits as soon as `cancel` flips to `true`.
async fn discovery_announce_loop(
    lan: LanDiscovery,
    sync: SyncEngine,
    listen_port: u16,
    mut cancel: tokio::sync::watch::Receiver<bool>,
) {
    let device_id = sync.device_id().to_string();
    let candidate = [lan_announce_candidate(listen_port)];
    loop {
        if *cancel.borrow() {
            return;
        }
        lan.announce(&device_id, &candidate).await;
        tokio::select! {
            () = tokio::time::sleep(std::time::Duration::from_secs(30)) => {}
            res = cancel.changed() => {
                if res.is_err() || *cancel.borrow() {
                    return;
                }
            }
        }
    }
}

/// Window each [`LanDiscovery::listen_all`] call listens for before
/// returning the peers seen. Matches the timeout the loop used before
/// discovery moved behind the trait.
const LAN_LISTEN_WINDOW: std::time::Duration = std::time::Duration::from_secs(15);

/// Listen for peer announcements on the LAN via the [`LanDiscovery`]
/// source and, for any trusted device we don't already have a session
/// to, kick off an outbound connect.
///
/// Each listen runs on `spawn_blocking` inside [`LanDiscovery::listen_all`]
/// with a 15 s window. Listen errors are logged and swallowed there,
/// surfacing as an empty peer set so the loop simply continues.
///
/// Exits as soon as `cancel` flips to `true`. The outer task races
/// `cancel.changed()` against the in-flight listen future, so shutdown
/// is observed immediately rather than waiting up to the 15 s blocking
/// timeout. The detached `spawn_blocking` thread will finish on its own
/// when the std-net call times out, but the async task no longer blocks
/// on it.
async fn discovery_listen_loop(
    lan: LanDiscovery,
    sync: SyncEngine,
    mut cancel: tokio::sync::watch::Receiver<bool>,
) {
    loop {
        if *cancel.borrow() {
            return;
        }
        let listen_fut = lan.listen_all(LAN_LISTEN_WINDOW);
        let peers = tokio::select! {
            res = cancel.changed() => {
                if res.is_err() || *cancel.borrow() {
                    tracing::debug!(
                        target: "cascade::backend::p2p",
                        "discovery listen loop cancelled",
                    );
                    return;
                }
                continue;
            }
            peers = listen_fut => peers,
        };
        for peer in peers {
            // Skip ourselves — multicast loopback can deliver our own
            // announcement back to us.
            if peer.device_id == sync.device_id() {
                continue;
            }
            if !sync.is_trusted(&peer.device_id).await {
                continue;
            }
            if sync.has_peer(&peer.device_id).await {
                continue;
            }
            if let Err(e) = sync
                .connect_to(crate::sync::Peer {
                    device_id: peer.device_id.clone(),
                    address: peer.address,
                })
                .await
            {
                tracing::debug!(
                    target: "cascade::backend::p2p",
                    "LAN discovery connect to {} at {} failed: {e:#}",
                    peer.device_id,
                    peer.address,
                );
            }
        }
    }
}

/// CLI entry point — construct a backend from a TOML config table.
///
/// Expected keys:
/// - `name` (required) — instance name; used to derive `id = "p2p-{name}"`
/// - `display_name` (optional) — human-readable label
/// - `device_name` (optional) — friendly name for the LOCAL device, used
///   by the sync engine when labelling conflict-copy paths. Falls back
///   to the short device id when unset.
/// - `data_dir` (optional) — base dir for index + block store;
///   defaults to `${HOME}/.config/cascade/p2p-{name}`
/// - `listen_addr` (optional) — `"host:port"` for the BEP listener
/// - `peers` (optional) — array of `{ device_id = "...", address = "host:port", name = "..." }`.
///   `name` is optional; when present it is used in conflict-copy paths
///   generated by that peer.
/// - `enable_discovery` (optional, default `false`) — opt in to
///   UDP-multicast LAN peer discovery. Requires `listen_addr` to be set.
/// - `enable_wan_gossip` (optional, default `false`) — broadcast the
///   local peer book to every connected peer every 60s and merge
///   inbound gossip into the local peer book, so devices learn about
///   each other transitively
/// - `stun_servers` (optional) — array of `host:port` STUN servers used
///   for NAT type detection at startup
pub fn create_backend(config: &toml::Value) -> Result<Box<dyn Backend>> {
    let name = config
        .get("name")
        .and_then(|v| v.as_str())
        .ok_or_else(|| anyhow::anyhow!("p2p backend requires 'name'"))?
        .to_string();
    let display_name = config
        .get("display_name")
        .and_then(|v| v.as_str())
        .unwrap_or(&name)
        .to_string();
    let data_dir = config
        .get("data_dir")
        .and_then(|v| v.as_str())
        .map_or_else(|| default_data_dir(&name), PathBuf::from);
    let listen_addr = config
        .get("listen_addr")
        .and_then(|v| v.as_str())
        .map(|s| {
            s.parse::<std::net::SocketAddr>()
                .with_context(|| format!("invalid listen_addr `{s}`"))
        })
        .transpose()?;
    let peers = parse_peers(config.get("peers"))?;
    let enable_discovery = config
        .get("enable_discovery")
        .and_then(toml::Value::as_bool)
        .unwrap_or(false);
    let device_name = config
        .get("device_name")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    let enable_wan_gossip = config
        .get("enable_wan_gossip")
        .and_then(toml::Value::as_bool)
        .unwrap_or(false);
    let stun_servers = config
        .get("stun_servers")
        .and_then(toml::Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(toml::Value::as_str)
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();
    let relay_endpoints = config
        .get("relay_endpoints")
        .and_then(toml::Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(toml::Value::as_str)
                .map(|s| {
                    s.parse::<std::net::SocketAddr>()
                        .with_context(|| format!("invalid relay endpoint `{s}`"))
                })
                .collect::<Result<Vec<_>>>()
        })
        .transpose()?
        .unwrap_or_default();
    let relay_shared_secret = config
        .get("relay_shared_secret")
        .and_then(|v| v.as_str())
        .map(parse_relay_shared_secret)
        .transpose()?;
    let enable_hole_punch = config
        .get("enable_hole_punch")
        .and_then(toml::Value::as_bool)
        .unwrap_or(true);
    let relay_volunteer = config
        .get("relay_volunteer")
        .and_then(|v| v.as_str())
        .map(parse_relay_volunteer)
        .transpose()?
        .unwrap_or_default();
    let max_relay_sessions = config
        .get("max_relay_sessions")
        .and_then(toml::Value::as_integer)
        .map(|raw| {
            u32::try_from(raw).with_context(|| format!("max_relay_sessions `{raw}` out of range"))
        })
        .transpose()?
        .unwrap_or(DEFAULT_MAX_RELAY_SESSIONS);
    let max_relay_bandwidth = config
        .get("max_relay_bandwidth")
        .and_then(toml::Value::as_integer)
        .map(|raw| {
            u64::try_from(raw).with_context(|| format!("max_relay_bandwidth `{raw}` out of range"))
        })
        .transpose()?
        .unwrap_or(DEFAULT_MAX_RELAY_BANDWIDTH_BYTES_PER_SEC);

    let instance_id = format!("p2p-{name}");
    let cfg = P2pBackendConfig {
        folder_id: instance_id.clone(),
        instance_id,
        display_name,
        index_path: data_dir.join("index.db"),
        block_store_root: data_dir.join("blocks"),
        identity_dir: data_dir.join("identity"),
        listen_addr,
        peers,
        enable_discovery,
        device_name,
        enable_wan_gossip,
        stun_servers,
        relay_endpoints,
        relay_shared_secret,
        enable_hole_punch,
        relay_volunteer,
        max_relay_sessions,
        max_relay_bandwidth,
    };

    let backend = P2pBackend::open(cfg)?;
    Ok(Box::new(backend))
}

fn parse_peers(value: Option<&toml::Value>) -> Result<Vec<ConfiguredPeer>> {
    let Some(arr) = value.and_then(|v| v.as_array()) else {
        return Ok(Vec::new());
    };
    let mut peers = Vec::with_capacity(arr.len());
    for (idx, item) in arr.iter().enumerate() {
        let table = item
            .as_table()
            .ok_or_else(|| anyhow::anyhow!("peers[{idx}] must be a table"))?;
        let device_id = table
            .get("device_id")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("peers[{idx}].device_id required"))?
            .to_string();
        let address = table
            .get("address")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("peers[{idx}].address required"))?
            .to_string();
        let name = table
            .get("name")
            .and_then(|v| v.as_str())
            .map(str::to_string);
        peers.push(ConfiguredPeer {
            device_id,
            address,
            name,
        });
    }
    Ok(peers)
}

/// Parse the relay shared secret from its 64-character hex string form.
///
/// The cascade relay HMAC-authenticates clients with a 32-byte key. The
/// TOML config carries the key as lowercase hex so operators can copy
/// it from `openssl rand -hex 32` output. Anything other than exactly
/// 64 hex digits is a configuration error — the field is too sensitive
/// to silently truncate or pad.
fn parse_relay_shared_secret(input: &str) -> Result<[u8; 32]> {
    if input.len() != 64 {
        anyhow::bail!(
            "relay_shared_secret must be 64 hex characters (32 bytes), got {}",
            input.len(),
        );
    }
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        let pair_start = i.checked_mul(2).with_context(|| "secret index overflow")?;
        let pair_end = pair_start
            .checked_add(2)
            .with_context(|| "secret index overflow")?;
        let pair = input
            .get(pair_start..pair_end)
            .with_context(|| "relay_shared_secret hex slice out of range")?;
        *byte = u8::from_str_radix(pair, 16)
            .with_context(|| format!("invalid hex pair `{pair}` in relay_shared_secret"))?;
    }
    Ok(out)
}

/// Parse the `relay_volunteer` policy from its lowercase string form.
///
/// Accepts exactly `off`, `explicit`, or `auto`. Any other value is a
/// configuration error rather than a silent fallback to the default —
/// an operator who typed `aut` deserves to be told, not to discover the
/// node quietly volunteering when they meant to turn it off.
fn parse_relay_volunteer(input: &str) -> Result<RelayVolunteer> {
    match input {
        "off" => Ok(RelayVolunteer::Off),
        "explicit" => Ok(RelayVolunteer::Explicit),
        "auto" => Ok(RelayVolunteer::Auto),
        other => {
            anyhow::bail!("relay_volunteer must be one of `off`, `explicit`, `auto`, got `{other}`")
        }
    }
}

fn default_data_dir(name: &str) -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("cascade")
        .join(format!("p2p-{name}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor as IoCursor;
    use tempfile::tempdir;

    fn make_backend() -> (tempfile::TempDir, P2pBackend) {
        let dir = tempdir().unwrap();
        let cfg = P2pBackendConfig {
            instance_id: "p2p-test".to_string(),
            folder_id: "p2p-test".to_string(),
            display_name: "Test".to_string(),
            index_path: dir.path().join("index.db"),
            block_store_root: dir.path().join("blocks"),
            identity_dir: dir.path().join("identity"),
            ..Default::default()
        };
        let backend = P2pBackend::open(cfg).unwrap();
        (dir, backend)
    }

    #[tokio::test]
    async fn upload_then_download_round_trips() {
        let (_dir, backend) = make_backend();
        let data = b"hello world".repeat(1000);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(data.clone());
        let entry = backend
            .upload(
                Path::new("hello.txt"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();
        assert_eq!(entry.name, "hello.txt");
        assert_eq!(entry.size, Some(data.len() as u64));

        let mut out: Vec<u8> = Vec::new();
        backend.download(&entry, &mut out).await.unwrap();
        assert_eq!(out, data);
    }

    #[tokio::test]
    async fn list_children_after_uploads() {
        let (_dir, backend) = make_backend();
        let mut reader = IoCursor::new(b"a".to_vec());
        backend
            .upload(
                Path::new("a.txt"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();
        let mut reader2 = IoCursor::new(b"b".to_vec());
        backend
            .upload(
                Path::new("b.txt"),
                &mut reader2,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();
        let kids = backend.list_children("root").await.unwrap();
        let names: Vec<_> = kids.iter().map(|e| e.name.clone()).collect();
        assert!(names.contains(&"a.txt".to_string()));
        assert!(names.contains(&"b.txt".to_string()));
    }

    #[tokio::test]
    async fn changes_after_upload() {
        let (_dir, backend) = make_backend();
        let (initial, c0) = backend.changes(None).await.unwrap();
        assert!(initial.is_empty());

        let mut reader = IoCursor::new(b"data".to_vec());
        backend
            .upload(
                Path::new("x.txt"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        let (deltas, _c1) = backend.changes(Some(&c0)).await.unwrap();
        assert_eq!(deltas.len(), 1);
        assert!(matches!(deltas[0], Change::Created(_)));
    }

    #[tokio::test]
    async fn delete_marks_tombstone_excluded_from_listing() {
        let (_dir, backend) = make_backend();
        let mut reader = IoCursor::new(b"x".to_vec());
        let entry = backend
            .upload(
                Path::new("x.txt"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();
        backend.delete(&entry).await.unwrap();
        let kids = backend.list_children("root").await.unwrap();
        assert!(kids.is_empty());
    }

    /// End-to-end: A uploads through the Backend trait, B connects, and
    /// B's `download()` succeeds even though B's local block store is
    /// empty — the missing blocks must be fetched from A over the wire.
    #[tokio::test]
    async fn cross_backend_download_via_peer_fetch() {
        fn open_with_folder(dir: &std::path::Path, name: &str) -> P2pBackend {
            let cfg = P2pBackendConfig {
                instance_id: format!("p2p-{name}"),
                folder_id: "shared".to_string(),
                display_name: name.to_string(),
                index_path: dir.join("index.db"),
                block_store_root: dir.join("blocks"),
                identity_dir: dir.join("identity"),
                ..Default::default()
            };
            P2pBackend::open(cfg).unwrap()
        }
        let dir_a = tempdir().unwrap();
        let dir_b = tempdir().unwrap();
        let backend_a = open_with_folder(dir_a.path(), "a");
        let backend_b = open_with_folder(dir_b.path(), "b");

        backend_a
            .sync()
            .trust(backend_b.sync().device_id().to_string())
            .await;
        backend_b
            .sync()
            .trust(backend_a.sync().device_id().to_string())
            .await;

        let (_cancel_tx_a, cancel_rx_a) = tokio::sync::watch::channel(false);
        let (addr_a, _a_task) = backend_a
            .sync()
            .start_listener("127.0.0.1:0".parse().unwrap(), cancel_rx_a)
            .await
            .unwrap();
        backend_b
            .sync()
            .connect_to(crate::sync::Peer {
                device_id: backend_a.sync().device_id().to_string(),
                address: addr_a,
            })
            .await
            .unwrap();

        let payload = b"peer-to-peer round trip".repeat(50);
        let mut reader = IoCursor::new(payload.clone());
        let entry_a = backend_a
            .upload(
                Path::new("shared.bin"),
                &mut reader,
                &FileId(format!("{}:root", backend_a.id())),
            )
            .await
            .unwrap();

        // Let the IndexUpdate broadcast and the handshake Index reach B.
        let mut found = None;
        for _ in 0..50 {
            tokio::time::sleep(std::time::Duration::from_millis(40)).await;
            if let Some(local) = backend_b.index.get("shared.bin").unwrap() {
                found = Some(local);
                break;
            }
        }
        let local_b = found.expect("B never received index update");
        assert_eq!(local_b.size, entry_a.size.unwrap());
        // B's block store is empty — download must hit the peer.
        for chunk in local_b.block_hashes.chunks(32) {
            let mut h = [0u8; 32];
            h.copy_from_slice(chunk);
            assert!(
                backend_b
                    .blocks
                    .get_block(&BlockHash(h))
                    .await
                    .unwrap()
                    .is_none()
            );
        }

        let entry_b = backend_b.metadata(Path::new("shared.bin")).await.unwrap();
        let mut out: Vec<u8> = Vec::new();
        backend_b.download(&entry_b, &mut out).await.unwrap();
        assert_eq!(out, payload);
    }

    /// A deterministic payload large enough to split into several
    /// 128 KB blocks. Each byte is `position % 251` (a prime, so the
    /// pattern does not align to any power-of-two block boundary),
    /// which makes a wrong slice trivially detectable.
    fn multi_block_payload(len: usize) -> Vec<u8> {
        (0..len).map(|i| u8::try_from(i % 251).unwrap()).collect()
    }

    #[tokio::test]
    async fn read_range_spans_block_boundary() {
        let (_dir, backend) = make_backend();
        // 3.5 blocks worth of data → four 128 KB blocks, last short.
        let block = 128 * 1024;
        let payload = multi_block_payload(block * 7 / 2);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("big.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        // A window straddling the first/second block boundary.
        let start = block - 100;
        let length = 200u32;
        let got = backend
            .read_range(&entry, u64::try_from(start).unwrap(), length)
            .await
            .unwrap();
        let end = start + usize::try_from(length).unwrap();
        assert_eq!(got, &payload[start..end]);
    }

    #[tokio::test]
    async fn read_range_single_block_sub_range() {
        let (_dir, backend) = make_backend();
        let block = 128 * 1024;
        let payload = multi_block_payload(block * 3);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("three.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        // Wholly inside the second block.
        let start = block + 17;
        let length = 64u32;
        let got = backend
            .read_range(&entry, u64::try_from(start).unwrap(), length)
            .await
            .unwrap();
        let end = start + usize::try_from(length).unwrap();
        assert_eq!(got, &payload[start..end]);
    }

    #[tokio::test]
    async fn read_range_clamps_length_past_eof() {
        let (_dir, backend) = make_backend();
        let payload = multi_block_payload(5000);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("small.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        // length runs well past EOF — result is truncated to the tail.
        let got = backend.read_range(&entry, 4000, 10_000).await.unwrap();
        assert_eq!(got, &payload[4000..]);
    }

    #[tokio::test]
    async fn read_range_whole_file() {
        let (_dir, backend) = make_backend();
        let payload = multi_block_payload(128 * 1024 * 2 + 99);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("whole.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        let len = u32::try_from(payload.len()).unwrap();
        let got = backend.read_range(&entry, 0, len).await.unwrap();
        assert_eq!(got, payload);
    }

    #[tokio::test]
    async fn read_range_offset_at_or_past_eof_is_empty() {
        let (_dir, backend) = make_backend();
        let payload = multi_block_payload(2048);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("eof.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        assert!(
            backend
                .read_range(&entry, 2048, 10)
                .await
                .unwrap()
                .is_empty()
        );
        assert!(
            backend
                .read_range(&entry, 99_999, 10)
                .await
                .unwrap()
                .is_empty()
        );
    }

    #[tokio::test]
    async fn read_range_zero_length_is_empty() {
        let (_dir, backend) = make_backend();
        let payload = multi_block_payload(2048);
        let mut reader: IoCursor<Vec<u8>> = IoCursor::new(payload.clone());
        let entry = backend
            .upload(
                Path::new("zero.bin"),
                &mut reader,
                &FileId("p2p-test:root".to_string()),
            )
            .await
            .unwrap();

        assert!(backend.read_range(&entry, 0, 0).await.unwrap().is_empty());
        assert!(backend.read_range(&entry, 100, 0).await.unwrap().is_empty());
    }

    /// Cross-backend: B reads a range from a file it has indexed but not
    /// cached. The fetch must pull ONLY the blocks covering the window
    /// from A, leaving the rest of B's block store empty — proof that
    /// the override does not reconstruct the whole file.
    #[tokio::test]
    async fn read_range_fetches_only_covering_blocks_from_peer() {
        fn open_with_folder(dir: &std::path::Path, name: &str) -> P2pBackend {
            let cfg = P2pBackendConfig {
                instance_id: format!("p2p-{name}"),
                folder_id: "shared".to_string(),
                display_name: name.to_string(),
                index_path: dir.join("index.db"),
                block_store_root: dir.join("blocks"),
                identity_dir: dir.join("identity"),
                ..Default::default()
            };
            P2pBackend::open(cfg).unwrap()
        }
        let dir_a = tempdir().unwrap();
        let dir_b = tempdir().unwrap();
        let backend_a = open_with_folder(dir_a.path(), "a");
        let backend_b = open_with_folder(dir_b.path(), "b");

        backend_a
            .sync()
            .trust(backend_b.sync().device_id().to_string())
            .await;
        backend_b
            .sync()
            .trust(backend_a.sync().device_id().to_string())
            .await;

        let (_cancel_tx_a, cancel_rx_a) = tokio::sync::watch::channel(false);
        let (addr_a, _a_task) = backend_a
            .sync()
            .start_listener("127.0.0.1:0".parse().unwrap(), cancel_rx_a)
            .await
            .unwrap();
        backend_b
            .sync()
            .connect_to(crate::sync::Peer {
                device_id: backend_a.sync().device_id().to_string(),
                address: addr_a,
            })
            .await
            .unwrap();

        // Five-block file (4 full 128 KB blocks + a short tail).
        let block = 128 * 1024;
        let payload = multi_block_payload(block * 4 + 1234);
        let mut reader = IoCursor::new(payload.clone());
        backend_a
            .upload(
                Path::new("range.bin"),
                &mut reader,
                &FileId(format!("{}:root", backend_a.id())),
            )
            .await
            .unwrap();

        // Wait for B to learn about the file via the index update.
        let mut found = None;
        for _ in 0..50 {
            tokio::time::sleep(std::time::Duration::from_millis(40)).await;
            if let Some(local) = backend_b.index.get("range.bin").unwrap() {
                found = Some(local);
                break;
            }
        }
        let local_b = found.expect("B never received index update");
        let total_blocks = local_b.block_hashes.len() / 32;
        assert_eq!(total_blocks, 5);

        // Read a window inside the third block only (index 2).
        let start = block * 2 + 50;
        let length = 300u32;
        let entry_b = backend_b.metadata(Path::new("range.bin")).await.unwrap();
        let got = backend_b
            .read_range(&entry_b, u64::try_from(start).unwrap(), length)
            .await
            .unwrap();
        let end = start + usize::try_from(length).unwrap();
        assert_eq!(got, &payload[start..end]);

        // Exactly one block — the covering one — should now be cached on
        // B; the other four must still be absent. This is the load-
        // bearing assertion: a whole-file reconstruction would have
        // cached all five.
        let mut cached = 0usize;
        for chunk in local_b.block_hashes.chunks(32) {
            let mut h = [0u8; 32];
            h.copy_from_slice(chunk);
            if backend_b
                .blocks
                .get_block(&BlockHash(h))
                .await
                .unwrap()
                .is_some()
            {
                cached += 1;
            }
        }
        assert_eq!(cached, 1, "only the covering block should be cached");
    }

    #[test]
    fn parse_relay_shared_secret_round_trips_32_bytes() {
        // A 64-char lowercase hex string round-trips to its 32 source
        // bytes exactly. Anything shorter, longer, or with non-hex
        // characters is rejected — silent truncation of an HMAC key
        // would substitute predictable bytes for the missing ones.
        let secret_hex = "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee";
        let parsed = parse_relay_shared_secret(secret_hex).unwrap();
        assert_eq!(parsed[0], 0x00);
        assert_eq!(parsed[1], 0x11);
        assert_eq!(parsed[31], 0xee);
    }

    #[test]
    fn parse_relay_shared_secret_rejects_wrong_length() {
        assert!(parse_relay_shared_secret("abcd").is_err());
        let too_long = "0".repeat(66);
        assert!(parse_relay_shared_secret(&too_long).is_err());
    }

    #[test]
    fn parse_relay_shared_secret_rejects_non_hex() {
        let bad = "zz".repeat(32);
        assert!(parse_relay_shared_secret(&bad).is_err());
    }

    #[test]
    fn p2p_backend_config_default_enables_hole_punch() {
        // Hole-punching is the only flag whose default differs from the
        // derived `Default` — this test guards the manual `Default` impl
        // against accidental regression to a derived all-false default
        // if someone re-adds `#[derive(Default)]`.
        let cfg = P2pBackendConfig::default();
        assert!(cfg.enable_hole_punch);
        assert!(!cfg.enable_discovery);
        assert!(!cfg.enable_wan_gossip);
        assert!(cfg.relay_endpoints.is_empty());
        assert!(cfg.relay_shared_secret.is_none());
    }

    /// Enabling LAN discovery must not block or panic on backend open.
    /// We can't reliably exercise the full multicast handshake on
    /// loopback in CI, so we just confirm the spawned loops come up
    /// cleanly and the backend can be dropped after a short delay.
    ///
    /// On drop, the backend's cancellation watch is flipped to `true`.
    /// We subscribe before drop and confirm the receiver sees the
    /// change, proving the spawned tasks will exit.
    #[tokio::test]
    async fn discovery_loop_starts_without_panicking() {
        let dir = tempdir().unwrap();
        let cfg = P2pBackendConfig {
            instance_id: "p2p-discovery".to_string(),
            folder_id: "p2p-discovery".to_string(),
            display_name: "Discovery".to_string(),
            index_path: dir.path().join("index.db"),
            block_store_root: dir.path().join("blocks"),
            identity_dir: dir.path().join("identity"),
            listen_addr: Some("127.0.0.1:0".parse().unwrap()),
            enable_discovery: true,
            ..Default::default()
        };
        let backend = P2pBackend::open(cfg).unwrap();
        let mut cancel_rx = backend.cancel.subscribe();
        assert!(!*cancel_rx.borrow());
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        drop(backend);
        // After drop, the cancel watch must have fired; spawned tasks
        // will observe `true` on their next tick and exit.
        cancel_rx.changed().await.unwrap();
        assert!(*cancel_rx.borrow());
    }
}
