// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(cascade_ffiFFI)
import cascade_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cascade_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cascade_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCascadeFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A running Cascade node, wrapping a [`NativeEngine`].
 *
 * Constructed with [`CascadeNode::new`], which builds the engine over a state
 * database and cache directory rooted at the caller-supplied config directory and
 * mounts a single local-files backend. The object owns the engine for its
 * lifetime; dropping it on the foreign side shuts the background workers down.
 */
public protocol CascadeNodeProtocol: AnyObject, Sendable {
    
    /**
     * List the entries of the directory at `path` (a VFS-absolute path).
     */
    func listDir(path: String) async throws  -> [DirEntry]
    
    /**
     * Pin the path pattern so matching files are kept on disk.
     */
    func pin(path: String) async throws 
    
    /**
     * Read the full contents of the file at `path` (a VFS-absolute path).
     */
    func readFile(path: String) async throws  -> Data
    
    /**
     * Start the engine's background workers (cache eviction).
     *
     * Idempotent in effect: a second call replaces the stored handle, leaving the
     * engine's single cancellation flag governing the workers.
     */
    func start() async throws 
    
    /**
     * Return the engine status as a JSON object.
     *
     * Serialising to JSON keeps the foreign surface a single string rather than a
     * mirror of the whole [`cascade_engine::EngineStatus`] tree, which the File
     * Provider only needs to display, not to branch on.
     */
    func status() async  -> String
    
    /**
     * Stop the engine's background workers, signalling them to quiesce.
     */
    func stop() async 
    
    /**
     * Unpin the path pattern. A no-op if no matching rule exists.
     */
    func unpin(path: String) async throws 
    
}
/**
 * A running Cascade node, wrapping a [`NativeEngine`].
 *
 * Constructed with [`CascadeNode::new`], which builds the engine over a state
 * database and cache directory rooted at the caller-supplied config directory and
 * mounts a single local-files backend. The object owns the engine for its
 * lifetime; dropping it on the foreign side shuts the background workers down.
 */
open class CascadeNode: CascadeNodeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cascade_ffi_fn_clone_cascadenode(self.handle, $0) }
    }
    /**
     * Build a node rooted at `config_dir`.
     *
     * Creates `config_dir` and its `files` subdirectory, opens (or creates) the
     * state database at `config_dir/state.db`, and mounts a local-files backend
     * over the `files` directory under the `local` VFS prefix. The engine is built
     * on the calling Tokio runtime — `UniFFI` drives this async constructor on the
     * runtime the rest of the methods also use, so the engine's captured runtime
     * handle is the one its later async work runs on.
     */
public convenience init(configDir: String)async throws  {
    let handle =
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_constructor_cascadenode_new(FfiConverterString.lower(configDir)
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_u64,
            completeFunc: ffi_cascade_ffi_rust_future_complete_u64,
            freeFunc: ffi_cascade_ffi_rust_future_free_u64,
            liftFunc: FfiConverterTypeCascadeNode_lift,
            errorHandler: FfiConverterTypeCascadeError_lift
        )
        
        .uniffiCloneHandle()
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cascade_ffi_fn_free_cascadenode(handle, $0) }
    }

    

    
    /**
     * List the entries of the directory at `path` (a VFS-absolute path).
     */
open func listDir(path: String)async throws  -> [DirEntry]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_list_dir(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cascade_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cascade_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeDirEntry.lift,
            errorHandler: FfiConverterTypeCascadeError_lift
        )
}
    
    /**
     * Pin the path pattern so matching files are kept on disk.
     */
open func pin(path: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_pin(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_void,
            completeFunc: ffi_cascade_ffi_rust_future_complete_void,
            freeFunc: ffi_cascade_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCascadeError_lift
        )
}
    
    /**
     * Read the full contents of the file at `path` (a VFS-absolute path).
     */
open func readFile(path: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_read_file(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cascade_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cascade_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeCascadeError_lift
        )
}
    
    /**
     * Start the engine's background workers (cache eviction).
     *
     * Idempotent in effect: a second call replaces the stored handle, leaving the
     * engine's single cancellation flag governing the workers.
     */
open func start()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_start(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_void,
            completeFunc: ffi_cascade_ffi_rust_future_complete_void,
            freeFunc: ffi_cascade_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCascadeError_lift
        )
}
    
    /**
     * Return the engine status as a JSON object.
     *
     * Serialising to JSON keeps the foreign surface a single string rather than a
     * mirror of the whole [`cascade_engine::EngineStatus`] tree, which the File
     * Provider only needs to display, not to branch on.
     */
open func status()async  -> String  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_status(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cascade_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cascade_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Stop the engine's background workers, signalling them to quiesce.
     */
open func stop()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_stop(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_void,
            completeFunc: ffi_cascade_ffi_rust_future_complete_void,
            freeFunc: ffi_cascade_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
    /**
     * Unpin the path pattern. A no-op if no matching rule exists.
     */
open func unpin(path: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cascade_ffi_fn_method_cascadenode_unpin(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_cascade_ffi_rust_future_poll_void,
            completeFunc: ffi_cascade_ffi_rust_future_complete_void,
            freeFunc: ffi_cascade_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeCascadeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCascadeNode: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CascadeNode

    public static func lift(_ handle: UInt64) throws -> CascadeNode {
        return CascadeNode(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CascadeNode) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CascadeNode {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CascadeNode, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCascadeNode_lift(_ handle: UInt64) throws -> CascadeNode {
    return try FfiConverterTypeCascadeNode.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCascadeNode_lower(_ value: CascadeNode) -> UInt64 {
    return FfiConverterTypeCascadeNode.lower(value)
}




/**
 * A single entry returned by [`CascadeNode::list_dir`].
 *
 * Mirrors [`cascade_engine::types::DirEntry`] across the FFI boundary as a plain
 * record the foreign side can map straight onto its own directory-entry type.
 */
public struct DirEntry: Equatable, Hashable {
    /**
     * The entry's final path segment (no parent path).
     */
    public var name: String
    /**
     * Whether the entry is a directory.
     */
    public var isDir: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The entry's final path segment (no parent path).
         */name: String, 
        /**
         * Whether the entry is a directory.
         */isDir: Bool) {
        self.name = name
        self.isDir = isDir
    }

    

    
}

#if compiler(>=6)
extension DirEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DirEntry {
        return
            try DirEntry(
                name: FfiConverterString.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DirEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lift(_ buf: RustBuffer) throws -> DirEntry {
    return try FfiConverterTypeDirEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lower(_ value: DirEntry) -> RustBuffer {
    return FfiConverterTypeDirEntry.lower(value)
}


/**
 * Errors surfaced to the foreign side.
 *
 * The engine works in [`anyhow::Error`]; every fallible bridge method collapses
 * that into one of these variants so Swift and Kotlin see a typed error rather
 * than an opaque string. The carried message is the underlying error's display
 * form, preserved for logging on the foreign side.
 */
public enum CascadeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The node's config directory could not be created or prepared.
     *
     * The field is named `detail` rather than `message` deliberately: UniFFI's
     * Kotlin bindgen maps each error variant onto a subclass of
     * `kotlin.Exception`, and a variant field literally called `message` collides
     * with `Throwable.message`, producing Kotlin that does not compile. Swift has
     * no such clash, so this rename only changes the (unread) field name on the
     * Swift side.
     */
    case Config(detail: String
    )
    /**
     * The engine could not be constructed or started.
     */
    case Engine(detail: String
    )
    /**
     * A directory listing failed.
     */
    case Listing(detail: String
    )
    /**
     * A file read failed.
     */
    case Read(detail: String
    )
    /**
     * A pin or unpin operation failed.
     */
    case Pin(detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CascadeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCascadeError: FfiConverterRustBuffer {
    typealias SwiftType = CascadeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CascadeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Config(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Engine(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Listing(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Read(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Pin(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CascadeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Config(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Engine(detail):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Listing(detail):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Read(detail):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Pin(detail):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCascadeError_lift(_ buf: RustBuffer) throws -> CascadeError {
    return try FfiConverterTypeCascadeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCascadeError_lower(_ value: CascadeError) -> RustBuffer {
    return FfiConverterTypeCascadeError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDirEntry: FfiConverterRustBuffer {
    typealias SwiftType = [DirEntry]

    public static func write(_ value: [DirEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDirEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DirEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [DirEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDirEntry.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureCascadeFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cascade_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_list_dir() != 316) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_pin() != 60454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_read_file() != 50188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_start() != 56155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_status() != 60127) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_stop() != 46138) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_method_cascadenode_unpin() != 40623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cascade_ffi_checksum_constructor_cascadenode_new() != 48453) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCascadeFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all