# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.
# Before the first release, this is a placeholder. CI replaces it on first tag.

class CascadeRelay < Formula
  desc "Opaque byte-pipe relay server for Cascade peers behind NATs"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-relay-v0.1.0/cascade-relay-aarch64-macos.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-relay-v0.1.0/cascade-relay-x86_64-macos.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-relay-v0.1.0/cascade-relay-aarch64-linux.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-relay-v0.1.0/cascade-relay-x86_64-linux.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "cascade-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cascade-relay --version")
  end
end
