// Companion shim for the UniFFI-generated bindings.
//
// The Kotlin bindgen in UniFFI 0.31 emits everything for CascadeNode except the
// wrapper for its async primary constructor (it prints "Note no constructor
// generated for this object as it is async."). The Swift bindgen does emit it,
// which is why the iOS node can call `try await CascadeNode(configDir:)`.
//
// Rather than hand-edit the generated cascade_ffi.kt (which is regenerated by the
// build and must stay verbatim), this file lives in the same `uniffi.cascade_ffi`
// package and the same Gradle module, so it can reach the `internal` FFI plumbing
// (UniffiLib, uniffiRustCallAsync) the wrapper needs. It reconstructs exactly the
// call the generated wrapper would have made: drive the constructor's Rust future
// through the u64 future family (object handles are u64) and lift the resulting
// handle into a CascadeNode.

package uniffi.cascade_ffi

/**
 * Construct a [CascadeNode] over the given config directory.
 *
 * Mirrors the generated async method wrappers: it lowers the argument, hands the
 * constructor future to [uniffiRustCallAsync] with the u64 poll/complete/free
 * family, and lifts the completed handle through [FfiConverterTypeCascadeNode].
 */
@Throws(CascadeException::class)
suspend fun cascadeNodeNew(configDir: String): CascadeNode =
    uniffiRustCallAsync(
        UniffiLib.uniffi_cascade_ffi_fn_constructor_cascadenode_new(
            FfiConverterString.lower(configDir),
        ),
        { future, callback, continuation ->
            UniffiLib.ffi_cascade_ffi_rust_future_poll_u64(future, callback, continuation)
        },
        { future, continuation ->
            UniffiLib.ffi_cascade_ffi_rust_future_complete_u64(future, continuation)
        },
        { future -> UniffiLib.ffi_cascade_ffi_rust_future_free_u64(future) },
        // The completed future yields the object handle; lift it into the wrapper.
        { handle -> FfiConverterTypeCascadeNode.lift(handle) },
        CascadeException.ErrorHandler,
    )
